import { useTranslation } from '../../i18n';

// Texts of the project file of a maintenance case in German, English and Spanish.
export const de = {
  loading: 'Projektakte wird geladen …', loadFailed: 'Die Projektakte konnte nicht geladen werden.', retry: 'Erneut laden',
  back: 'Zur Instandhaltung', save: 'Speichern', cancel: 'Abbrechen', edit: 'Bearbeiten', remove: 'Entfernen',
  delete: 'Löschen', add: 'Hinzufügen', yes: 'Ja', no: 'Nein', saved: 'Gespeichert.', close: 'Schließen',
  readOnly: 'Nur Lesen: Ihre Rolle ändert diese Akte nicht.', projectFile: 'Projektakte', open: 'Öffnen',
  tabOverview: 'Übersicht', tabWork: 'Arbeitspakete & Abhängigkeiten', tabAppointments: 'Termine',
  tabProcurement: 'Angebote, Aufträge & Nachträge', tabCosts: 'Rechnungen & Kosten', tabProtocols: 'Protokolle',
  tabDocuments: 'Dokumente', sections: 'Bereiche der Projektakte',
  status_open: 'Offen', status_in_progress: 'In Bearbeitung', status_completed: 'Erledigt', status_cancelled: 'Abgebrochen',
  to_open: 'Wieder öffnen', to_in_progress: 'Bearbeitung beginnen', to_completed: 'Akte abschließen',
  to_cancelled: 'Akte abbrechen', reasonTitle: 'Grund für den Statuswechsel', reason: 'Grund', blocked: 'Noch nicht möglich',
  statusChanged: 'Status geändert.',
  facts: 'Angaben', property: 'Objekt', unit: 'Einheit', category: 'Kategorie', priority: 'Priorität',
  reportedBy: 'Gemeldet von', assignee: 'Zuständig', dueDate: 'Fällig am', legacyContractor: 'Handwerker (Freitext)',
  legacyAppointment: 'Termin (Freitext)', description: 'Beschreibung', editCase: 'Akte bearbeiten', title: 'Titel',
  priority_low: 'Niedrig', priority_medium: 'Mittel', priority_high: 'Hoch', priority_urgent: 'Dringend',
  budget: 'Budget (brutto)', ordered: 'Beauftragt', invoiced: 'Abgerechnet', paid: 'Bezahlt',
  pendingChanges: 'Nachträge zur Entscheidung', openToInvoice: 'Noch abzurechnen', openToPay: 'Noch zu zahlen',
  remainingBudget: 'Budget verbleibend', warnings: 'Hinweise', history: 'Verlauf', noHistory: 'Noch kein Verlauf.',
  changedBy: 'von', created: 'Angelegt',
  craftsmen: 'Handwerker & Beteiligte', addCraftsman: 'Kontakt zuordnen', noCraftsmen: 'Noch niemand zugeordnet.',
  contact: 'Kontakt', trade: 'Gewerk', role: 'Rolle', role_contractor: 'Handwerker', role_expert: 'Gutachter',
  role_other: 'Sonstige', notes: 'Notizen', contactMissing: 'Kontakt gelöscht', noContact: 'Ohne Kontakt',
  addPackage: 'Arbeitspaket anlegen', editPackage: 'Arbeitspaket bearbeiten', noPackages: 'Noch keine Arbeitspakete.',
  phase: 'Phase', kind: 'Art', kind_work: 'Arbeit', kind_milestone: 'Meilenstein', plannedStart: 'Beginn (geplant)',
  plannedEnd: 'Ende (geplant)', wp_planned: 'geplant', wp_in_progress: 'in Arbeit', wp_done: 'erledigt',
  wp_cancelled: 'entfällt', start: 'Beginnen', finish: 'Erledigt', drop: 'Entfällt', reopen: 'Wieder öffnen',
  replan: 'Wieder einplanen', waitsFor: 'Wartet auf', after: 'Nach', addDependency: 'Abhängigkeit hinzufügen',
  predecessor: 'Vorgänger (zuerst)', successor: 'Nachfolger (danach)',
  dependencyHint: 'Der Nachfolger beginnt erst, wenn der Vorgänger erledigt ist. Kreise werden abgelehnt.',
  scheduleConflicts: 'Terminplan prüfen', confirmDeletePackage: 'Arbeitspaket „{{title}}“ löschen?',
  sortOrder: 'Reihenfolge', removeDependency: 'Abhängigkeit entfernen',
  addAppointment: 'Termin anlegen', editAppointment: 'Termin bearbeiten', noAppointments: 'Noch keine Termine.',
  date: 'Datum', time: 'Uhrzeit', location: 'Ort', appt_inspection: 'Begehung', appt_execution: 'Ausführung',
  appt_acceptance: 'Abnahme', appt_other: 'Sonstiges', workPackage: 'Arbeitspaket', inCalendar: 'Zum Kalender',
  confirmDeleteAppointment: 'Termin löschen? Er wird auch aus dem Kalender entfernt.',
  quotes: 'Angebote', addQuote: 'Angebot erfassen', editQuote: 'Angebot bearbeiten', noQuotes: 'Noch keine Angebote.',
  supplier: 'Anbieter', quoteNumber: 'Angebotsnummer', quoteDate: 'Angebotsdatum', validUntil: 'Bindefrist',
  net: 'Netto', gross: 'Brutto', expired: 'abgelaufen', quote_received: 'eingegangen', quote_accepted: 'beauftragt',
  quote_rejected: 'abgelehnt', accept: 'Beauftragen', reject: 'Ablehnen', acceptTitle: 'Angebot beauftragen',
  orderNumber: 'Auftragsnummer', orderDate: 'Auftragsdatum', note: 'Notiz',
  rejectCompeting: 'Andere Angebote dieses Arbeitspakets ablehnen', rejectTitle: 'Angebot ablehnen',
  confirmDeleteQuote: 'Angebot löschen?', supplierHint: 'Leer lassen, um den Namen des Kontakts zu übernehmen.',
  orders: 'Aufträge', noOrders: 'Noch keine Aufträge. Ein Auftrag entsteht aus einem beauftragten Angebot.',
  order: 'Auftrag', order_active: 'aktiv', order_completed: 'abgeschlossen', order_cancelled: 'storniert',
  orderedTotal: 'Summe inkl. genehmigter Nachträge', completeOrder: 'Abschließen', cancelOrder: 'Stornieren',
  cancelOrderTitle: 'Auftrag stornieren', confirmCompleteOrder: 'Auftrag als abgeschlossen markieren?',
  changeOrders: 'Nachträge', addChangeOrder: 'Nachtrag erfassen', changeTitle: 'Bezeichnung',
  changeReason: 'Begründung', change_proposed: 'zur Entscheidung', change_approved: 'genehmigt',
  change_rejected: 'abgelehnt', approve: 'Genehmigen', amountsHint: 'Minderungen mit negativem Betrag erfassen.',
  confirmDeleteChange: 'Nachtrag löschen?', noChangeOrders: 'Keine Nachträge.',
  costSummary: 'Kosten der Akte', byOrder: 'Je Auftrag', invoices: 'Rechnungen',
  noInvoices: 'Noch keine Rechnungen zugeordnet.', addInvoice: 'Neue Rechnung erfassen',
  linkInvoice: 'Vorhandene Rechnung zuordnen', invoiceNumber: 'Rechnungsnummer', invoiceDate: 'Rechnungsdatum',
  vatRate: 'USt-Satz (%)', paymentTerms: 'Zahlungsbedingungen', unlink: 'Zuordnung lösen',
  confirmUnlinkInvoice: 'Rechnung von diesem Auftrag lösen? Die Rechnung selbst bleibt bestehen.',
  payments: 'Zahlungen', addPayment: 'Zahlung zuordnen', booking: 'Buchung', free: 'frei', amount: 'Betrag',
  noPayments: 'Keine Zahlung zugeordnet.', search: 'Suchen', loadMore: 'Weitere laden', nothingFound: 'Nichts gefunden.',
  allProperties: 'Auch Buchungen anderer Objekte zeigen',
  costRule: 'Beauftragt, abgerechnet und bezahlt werden aus Aufträgen, Rechnungen und Buchungen abgeleitet; die Akte bucht nichts selbst.',
  choose: 'Auswählen', invoice_open: 'offen', invoice_paid: 'bezahlt', invoice_partial: 'teilweise bezahlt',
  invoice_overdue: 'überfällig', invoice_cancelled: 'storniert', confirmRemovePayment: 'Zahlungszuordnung entfernen?',
  addProtocol: 'Protokoll anlegen', editProtocol: 'Protokoll bearbeiten', noProtocols: 'Noch keine Protokolle.',
  protocolType: 'Art', ptype_acceptance: 'Abnahme', ptype_inspection: 'Begehung', ptype_site_visit: 'Ortstermin',
  protocolDate: 'Datum', participants: 'Teilnehmende', result: 'Ergebnis', result_accepted: 'abgenommen',
  result_accepted_with_defects: 'abgenommen mit Mängeln', result_refused: 'Abnahme verweigert', defects: 'Mängel',
  addDefect: 'Mangel hinzufügen', defectTitle: 'Mangel', severity: 'Gewicht', severity_minor: 'geringfügig',
  severity_major: 'erheblich', severity_critical: 'kritisch', defectDue: 'Frist', photos: 'Fotos',
  noPhotos: 'Keine Fotos in der Akte. Fotos unter „Dokumente“ hochladen.', draft: 'Entwurf', final: 'abgeschlossen',
  preview: 'Vorschau', showPdf: 'PDF anzeigen', finalize: 'Abschließen & archivieren',
  finalizeConfirm: 'Das Protokoll wird als PDF erzeugt und unveränderlich archiviert. Danach sind keine Änderungen mehr möglich. Fortfahren?',
  finalized: 'Protokoll abgeschlossen und archiviert.', integrity_verified: 'Original geprüft',
  integrity_mismatch: 'Weicht vom archivierten Original ab', confirmDeleteProtocol: 'Protokollentwurf löschen?',
  pdfTitle: 'Protokoll (PDF)', noResult: 'ohne Ergebnis', defectCount: '{{count}} Mängel',
  documents: 'Dokumente', noDocuments: 'Noch keine Dokumente.', uploadDocument: 'Dokument hochladen',
  linkDocument: 'Vorhandenes Dokument zuordnen', docRole: 'Zuordnung', docRole_damage_photo: 'Schadensfoto',
  docRole_quote: 'Angebot', docRole_order: 'Auftrag', docRole_invoice: 'Rechnung', docRole_protocol: 'Protokoll',
  docRole_report: 'Bericht/Gutachten', docRole_other: 'Sonstiges', docRole_change_order: 'Nachtrag',
  damagePhotos: 'Schadensfotos', uploading: 'Wird hochgeladen …', file: 'Datei', uploadFailed: 'Upload fehlgeschlagen',
  confirmUnlinkDocument: 'Dokument von der Akte lösen? Das Dokument selbst bleibt bestehen.',
};

export const en = {
  loading: 'Loading project file …', loadFailed: 'The project file could not be loaded.', retry: 'Reload',
  back: 'Back to maintenance', save: 'Save', cancel: 'Cancel', edit: 'Edit', remove: 'Remove',
  delete: 'Delete', add: 'Add', yes: 'Yes', no: 'No', saved: 'Saved.', close: 'Close',
  readOnly: 'Read only: your role does not change this file.', projectFile: 'Project file', open: 'Open',
  tabOverview: 'Overview', tabWork: 'Work packages & dependencies', tabAppointments: 'Appointments',
  tabProcurement: 'Quotes, orders & change orders', tabCosts: 'Invoices & costs', tabProtocols: 'Protocols',
  tabDocuments: 'Documents', sections: 'Sections of the project file',
  status_open: 'Open', status_in_progress: 'In progress', status_completed: 'Completed', status_cancelled: 'Cancelled',
  to_open: 'Reopen', to_in_progress: 'Start work', to_completed: 'Complete file',
  to_cancelled: 'Cancel file', reasonTitle: 'Reason for the status change', reason: 'Reason', blocked: 'Not possible yet',
  statusChanged: 'Status changed.',
  facts: 'Details', property: 'Property', unit: 'Unit', category: 'Category', priority: 'Priority',
  reportedBy: 'Reported by', assignee: 'Assignee', dueDate: 'Due on', legacyContractor: 'Craftsman (free text)',
  legacyAppointment: 'Appointment (free text)', description: 'Description', editCase: 'Edit file', title: 'Title',
  priority_low: 'Low', priority_medium: 'Medium', priority_high: 'High', priority_urgent: 'Urgent',
  budget: 'Budget (gross)', ordered: 'Ordered', invoiced: 'Invoiced', paid: 'Paid',
  pendingChanges: 'Change orders awaiting decision', openToInvoice: 'Still to invoice', openToPay: 'Still to pay',
  remainingBudget: 'Budget remaining', warnings: 'Notes', history: 'History', noHistory: 'No history yet.',
  changedBy: 'by', created: 'Created',
  craftsmen: 'Craftsmen & parties', addCraftsman: 'Assign contact', noCraftsmen: 'Nobody assigned yet.',
  contact: 'Contact', trade: 'Trade', role: 'Role', role_contractor: 'Craftsman', role_expert: 'Expert',
  role_other: 'Other', notes: 'Notes', contactMissing: 'Contact deleted', noContact: 'No contact',
  addPackage: 'Add work package', editPackage: 'Edit work package', noPackages: 'No work packages yet.',
  phase: 'Phase', kind: 'Type', kind_work: 'Work', kind_milestone: 'Milestone', plannedStart: 'Planned start',
  plannedEnd: 'Planned end', wp_planned: 'planned', wp_in_progress: 'in progress', wp_done: 'done',
  wp_cancelled: 'dropped', start: 'Start', finish: 'Done', drop: 'Drop', reopen: 'Reopen',
  replan: 'Plan again', waitsFor: 'Waits for', after: 'After', addDependency: 'Add dependency',
  predecessor: 'Predecessor (first)', successor: 'Successor (then)',
  dependencyHint: 'The successor starts only when the predecessor is done. Cycles are refused.',
  scheduleConflicts: 'Check the schedule', confirmDeletePackage: 'Delete work package “{{title}}”?',
  sortOrder: 'Order', removeDependency: 'Remove dependency',
  addAppointment: 'Add appointment', editAppointment: 'Edit appointment', noAppointments: 'No appointments yet.',
  date: 'Date', time: 'Time', location: 'Location', appt_inspection: 'Inspection', appt_execution: 'Execution',
  appt_acceptance: 'Acceptance', appt_other: 'Other', workPackage: 'Work package', inCalendar: 'Open calendar',
  confirmDeleteAppointment: 'Delete appointment? It is also removed from the calendar.',
  quotes: 'Quotes', addQuote: 'Record quote', editQuote: 'Edit quote', noQuotes: 'No quotes yet.',
  supplier: 'Supplier', quoteNumber: 'Quote number', quoteDate: 'Quote date', validUntil: 'Valid until',
  net: 'Net', gross: 'Gross', expired: 'expired', quote_received: 'received', quote_accepted: 'ordered',
  quote_rejected: 'rejected', accept: 'Award order', reject: 'Reject', acceptTitle: 'Award order for quote',
  orderNumber: 'Order number', orderDate: 'Order date', note: 'Note',
  rejectCompeting: 'Reject the other quotes of this work package', rejectTitle: 'Reject quote',
  confirmDeleteQuote: 'Delete quote?', supplierHint: 'Leave empty to use the contact’s name.',
  orders: 'Orders', noOrders: 'No orders yet. An order is created from an accepted quote.',
  order: 'Order', order_active: 'active', order_completed: 'completed', order_cancelled: 'cancelled',
  orderedTotal: 'Total incl. approved change orders', completeOrder: 'Complete', cancelOrder: 'Cancel',
  cancelOrderTitle: 'Cancel order', confirmCompleteOrder: 'Mark the order as completed?',
  changeOrders: 'Change orders', addChangeOrder: 'Record change order', changeTitle: 'Description',
  changeReason: 'Reason', change_proposed: 'awaiting decision', change_approved: 'approved',
  change_rejected: 'rejected', approve: 'Approve', amountsHint: 'Record reductions with a negative amount.',
  confirmDeleteChange: 'Delete change order?', noChangeOrders: 'No change orders.',
  costSummary: 'Costs of the file', byOrder: 'Per order', invoices: 'Invoices',
  noInvoices: 'No invoices linked yet.', addInvoice: 'Record new invoice',
  linkInvoice: 'Link existing invoice', invoiceNumber: 'Invoice number', invoiceDate: 'Invoice date',
  vatRate: 'VAT rate (%)', paymentTerms: 'Payment terms', unlink: 'Unlink',
  confirmUnlinkInvoice: 'Unlink the invoice from this order? The invoice itself remains.',
  payments: 'Payments', addPayment: 'Allocate payment', booking: 'Booking', free: 'free', amount: 'Amount',
  noPayments: 'No payment allocated.', search: 'Search', loadMore: 'Load more', nothingFound: 'Nothing found.',
  allProperties: 'Also show bookings of other properties',
  costRule: 'Ordered, invoiced and paid are derived from orders, invoices and bookings; the file books nothing itself.',
  choose: 'Select', invoice_open: 'open', invoice_paid: 'paid', invoice_partial: 'partly paid',
  invoice_overdue: 'overdue', invoice_cancelled: 'cancelled', confirmRemovePayment: 'Remove payment allocation?',
  addProtocol: 'Add protocol', editProtocol: 'Edit protocol', noProtocols: 'No protocols yet.',
  protocolType: 'Type', ptype_acceptance: 'Acceptance', ptype_inspection: 'Inspection', ptype_site_visit: 'Site visit',
  protocolDate: 'Date', participants: 'Participants', result: 'Result', result_accepted: 'accepted',
  result_accepted_with_defects: 'accepted with defects', result_refused: 'acceptance refused', defects: 'Defects',
  addDefect: 'Add defect', defectTitle: 'Defect', severity: 'Severity', severity_minor: 'minor',
  severity_major: 'major', severity_critical: 'critical', defectDue: 'Deadline', photos: 'Photos',
  noPhotos: 'No photos in the file. Upload photos under “Documents”.', draft: 'Draft', final: 'final',
  preview: 'Preview', showPdf: 'Show PDF', finalize: 'Finalize & archive',
  finalizeConfirm: 'The protocol is rendered as a PDF and archived immutably. No changes are possible afterwards. Continue?',
  finalized: 'Protocol finalized and archived.', integrity_verified: 'Original verified',
  integrity_mismatch: 'Differs from the archived original', confirmDeleteProtocol: 'Delete protocol draft?',
  pdfTitle: 'Protocol (PDF)', noResult: 'no result', defectCount: '{{count}} defects',
  documents: 'Documents', noDocuments: 'No documents yet.', uploadDocument: 'Upload document',
  linkDocument: 'Link existing document', docRole: 'Role', docRole_damage_photo: 'Damage photo',
  docRole_quote: 'Quote', docRole_order: 'Order', docRole_invoice: 'Invoice', docRole_protocol: 'Protocol',
  docRole_report: 'Report/expert opinion', docRole_other: 'Other', docRole_change_order: 'Change order',
  damagePhotos: 'Damage photos', uploading: 'Uploading …', file: 'File', uploadFailed: 'Upload failed',
  confirmUnlinkDocument: 'Unlink the document from the file? The document itself remains.',
};

export const es = {
  loading: 'Cargando expediente …', loadFailed: 'No se pudo cargar el expediente.', retry: 'Volver a cargar',
  back: 'Volver a mantenimiento', save: 'Guardar', cancel: 'Cancelar', edit: 'Editar', remove: 'Quitar',
  delete: 'Eliminar', add: 'Añadir', yes: 'Sí', no: 'No', saved: 'Guardado.', close: 'Cerrar',
  readOnly: 'Solo lectura: su rol no modifica este expediente.', projectFile: 'Expediente del proyecto', open: 'Abrir',
  tabOverview: 'Resumen', tabWork: 'Paquetes de trabajo y dependencias', tabAppointments: 'Citas',
  tabProcurement: 'Ofertas, pedidos y suplementos', tabCosts: 'Facturas y costes', tabProtocols: 'Actas',
  tabDocuments: 'Documentos', sections: 'Secciones del expediente',
  status_open: 'Abierto', status_in_progress: 'En curso', status_completed: 'Terminado', status_cancelled: 'Cancelado',
  to_open: 'Reabrir', to_in_progress: 'Iniciar trabajos', to_completed: 'Cerrar expediente',
  to_cancelled: 'Cancelar expediente', reasonTitle: 'Motivo del cambio de estado', reason: 'Motivo',
  blocked: 'Todavía no es posible', statusChanged: 'Estado cambiado.',
  facts: 'Datos', property: 'Inmueble', unit: 'Unidad', category: 'Categoría', priority: 'Prioridad',
  reportedBy: 'Notificado por', assignee: 'Responsable', dueDate: 'Vence el', legacyContractor: 'Artesano (texto libre)',
  legacyAppointment: 'Cita (texto libre)', description: 'Descripción', editCase: 'Editar expediente', title: 'Título',
  priority_low: 'Baja', priority_medium: 'Media', priority_high: 'Alta', priority_urgent: 'Urgente',
  budget: 'Presupuesto (bruto)', ordered: 'Encargado', invoiced: 'Facturado', paid: 'Pagado',
  pendingChanges: 'Suplementos pendientes de decisión', openToInvoice: 'Pendiente de facturar',
  openToPay: 'Pendiente de pagar', remainingBudget: 'Presupuesto restante', warnings: 'Avisos', history: 'Historial',
  noHistory: 'Todavía no hay historial.', changedBy: 'por', created: 'Creado',
  craftsmen: 'Artesanos y participantes', addCraftsman: 'Asignar contacto', noCraftsmen: 'Nadie asignado todavía.',
  contact: 'Contacto', trade: 'Oficio', role: 'Rol', role_contractor: 'Artesano', role_expert: 'Perito',
  role_other: 'Otros', notes: 'Notas', contactMissing: 'Contacto eliminado', noContact: 'Sin contacto',
  addPackage: 'Crear paquete de trabajo', editPackage: 'Editar paquete de trabajo',
  noPackages: 'Todavía no hay paquetes de trabajo.', phase: 'Fase', kind: 'Tipo', kind_work: 'Trabajo',
  kind_milestone: 'Hito', plannedStart: 'Inicio previsto', plannedEnd: 'Fin previsto', wp_planned: 'previsto',
  wp_in_progress: 'en curso', wp_done: 'hecho', wp_cancelled: 'suprimido', start: 'Iniciar', finish: 'Hecho',
  drop: 'Suprimir', reopen: 'Reabrir', replan: 'Volver a planificar', waitsFor: 'Espera a', after: 'Después de',
  addDependency: 'Añadir dependencia', predecessor: 'Predecesor (primero)', successor: 'Sucesor (después)',
  dependencyHint: 'El sucesor solo empieza cuando el predecesor está hecho. Los ciclos se rechazan.',
  scheduleConflicts: 'Revisar el calendario', confirmDeletePackage: '¿Eliminar el paquete de trabajo «{{title}}»?',
  sortOrder: 'Orden', removeDependency: 'Quitar dependencia',
  addAppointment: 'Crear cita', editAppointment: 'Editar cita', noAppointments: 'Todavía no hay citas.',
  date: 'Fecha', time: 'Hora', location: 'Lugar', appt_inspection: 'Inspección', appt_execution: 'Ejecución',
  appt_acceptance: 'Recepción', appt_other: 'Otros', workPackage: 'Paquete de trabajo', inCalendar: 'Ir al calendario',
  confirmDeleteAppointment: '¿Eliminar la cita? También se quita del calendario.',
  quotes: 'Ofertas', addQuote: 'Registrar oferta', editQuote: 'Editar oferta', noQuotes: 'Todavía no hay ofertas.',
  supplier: 'Proveedor', quoteNumber: 'Número de oferta', quoteDate: 'Fecha de la oferta', validUntil: 'Válida hasta',
  net: 'Neto', gross: 'Bruto', expired: 'vencida', quote_received: 'recibida', quote_accepted: 'encargada',
  quote_rejected: 'rechazada', accept: 'Encargar', reject: 'Rechazar', acceptTitle: 'Encargar la oferta',
  orderNumber: 'Número de pedido', orderDate: 'Fecha del pedido', note: 'Nota',
  rejectCompeting: 'Rechazar las demás ofertas de este paquete', rejectTitle: 'Rechazar oferta',
  confirmDeleteQuote: '¿Eliminar la oferta?', supplierHint: 'Déjelo vacío para usar el nombre del contacto.',
  orders: 'Pedidos', noOrders: 'Todavía no hay pedidos. Un pedido nace de una oferta encargada.',
  order: 'Pedido', order_active: 'activo', order_completed: 'terminado', order_cancelled: 'anulado',
  orderedTotal: 'Total con suplementos aprobados', completeOrder: 'Terminar', cancelOrder: 'Anular',
  cancelOrderTitle: 'Anular pedido', confirmCompleteOrder: '¿Marcar el pedido como terminado?',
  changeOrders: 'Suplementos', addChangeOrder: 'Registrar suplemento', changeTitle: 'Denominación',
  changeReason: 'Justificación', change_proposed: 'pendiente de decisión', change_approved: 'aprobado',
  change_rejected: 'rechazado', approve: 'Aprobar', amountsHint: 'Registre las reducciones con importe negativo.',
  confirmDeleteChange: '¿Eliminar el suplemento?', noChangeOrders: 'Sin suplementos.',
  costSummary: 'Costes del expediente', byOrder: 'Por pedido', invoices: 'Facturas',
  noInvoices: 'Todavía no hay facturas asignadas.', addInvoice: 'Registrar factura nueva',
  linkInvoice: 'Asignar factura existente', invoiceNumber: 'Número de factura', invoiceDate: 'Fecha de factura',
  vatRate: 'Tipo de IVA (%)', paymentTerms: 'Condiciones de pago', unlink: 'Desvincular',
  confirmUnlinkInvoice: '¿Desvincular la factura de este pedido? La factura se conserva.',
  payments: 'Pagos', addPayment: 'Asignar pago', booking: 'Asiento', free: 'libre', amount: 'Importe',
  noPayments: 'Ningún pago asignado.', search: 'Buscar', loadMore: 'Cargar más', nothingFound: 'Sin resultados.',
  allProperties: 'Mostrar también asientos de otros inmuebles',
  costRule: 'Encargado, facturado y pagado se derivan de pedidos, facturas y asientos; el expediente no contabiliza nada.',
  choose: 'Elegir', invoice_open: 'abierta', invoice_paid: 'pagada', invoice_partial: 'pagada en parte',
  invoice_overdue: 'vencida', invoice_cancelled: 'anulada', confirmRemovePayment: '¿Quitar la asignación del pago?',
  addProtocol: 'Crear acta', editProtocol: 'Editar acta', noProtocols: 'Todavía no hay actas.',
  protocolType: 'Tipo', ptype_acceptance: 'Recepción', ptype_inspection: 'Inspección', ptype_site_visit: 'Visita',
  protocolDate: 'Fecha', participants: 'Participantes', result: 'Resultado', result_accepted: 'recibido',
  result_accepted_with_defects: 'recibido con defectos', result_refused: 'recepción rechazada', defects: 'Defectos',
  addDefect: 'Añadir defecto', defectTitle: 'Defecto', severity: 'Gravedad', severity_minor: 'leve',
  severity_major: 'importante', severity_critical: 'crítico', defectDue: 'Plazo', photos: 'Fotos',
  noPhotos: 'No hay fotos en el expediente. Súbalas en «Documentos».', draft: 'Borrador', final: 'cerrada',
  preview: 'Vista previa', showPdf: 'Ver PDF', finalize: 'Cerrar y archivar',
  finalizeConfirm: 'El acta se genera como PDF y se archiva de forma inalterable. Después no se puede modificar. ¿Continuar?',
  finalized: 'Acta cerrada y archivada.', integrity_verified: 'Original comprobado',
  integrity_mismatch: 'Difiere del original archivado', confirmDeleteProtocol: '¿Eliminar el borrador del acta?',
  pdfTitle: 'Acta (PDF)', noResult: 'sin resultado', defectCount: '{{count}} defectos',
  documents: 'Documentos', noDocuments: 'Todavía no hay documentos.', uploadDocument: 'Subir documento',
  linkDocument: 'Asignar documento existente', docRole: 'Asignación', docRole_damage_photo: 'Foto del daño',
  docRole_quote: 'Oferta', docRole_order: 'Pedido', docRole_invoice: 'Factura', docRole_protocol: 'Acta',
  docRole_report: 'Informe/peritaje', docRole_other: 'Otros', docRole_change_order: 'Suplemento',
  damagePhotos: 'Fotos del daño', uploading: 'Subiendo …', file: 'Archivo', uploadFailed: 'Error al subir',
  confirmUnlinkDocument: '¿Desvincular el documento del expediente? El documento se conserva.',
};

export function fill(text, values) {
  return Object.entries(values || {}).reduce((result, [key, value]) => result.replace(`{{${key}}}`, value), text);
}

export function useProjectText() {
  const { locale } = useTranslation();
  const tx = locale?.startsWith('en') ? en : locale?.startsWith('es') ? es : de;
  return { tx, locale: locale || 'de-DE' };
}
