export const workflowLanguages = {
  "de-DE": {
    "eyebrow": "Mieterwechsel",
    "templatesTitle": "Vorlagen & Abläufe",
    "changeTitle": "Wechselakte",
    "propertyScope": "Objekt",
    "unitScope": "Einheit",
    "objectDefault": "Objektstandard",
    "unitOverride": "Einheitsabweichung",
    "move_in": "Einzug",
    "move_out": "Auszug",
    "turnover": "Auszug & Einzug",
    "version": "Version {{version}}",
    "draft": "Entwurf",
    "published": "Veröffentlicht",
    "retired": "Ausgemustert",
    "save": "Entwurf speichern",
    "publish": "Version veröffentlichen",
    "working": "Wird gespeichert …",
    "refresh": "Neu laden",
    "close": "Schließen",
    "unknownTitle": "Antwort des Servers unklar",
    "unknownBody": "Der Befehl bleibt unverändert gespeichert. Nur die exakte Wiederholung mit demselben Schlüssel ist sicher.",
    "retryExact": "Exakt wiederholen",
    "conflictTitle": "Stand wurde zwischenzeitlich geändert",
    "conflictBody": "Lokale Eingaben bleiben erhalten. Bitte den aktuellen Stand bewusst neu prüfen.",
    "reviewCurrent": "Aktuellen Stand prüfen",
    "errorTitle": "Aktion fehlgeschlagen",
    "addStep": "Schritt hinzufügen",
    "removeStep": "Schritt entfernen",
    "moveUp": "Nach oben",
    "moveDown": "Nach unten",
    "stepTitle": "Schritt",
    "title": "Titel",
    "description": "Beschreibung",
    "requirement": "Anforderung",
    "required": "Pflicht",
    "optional": "Optional",
    "anchor": "Terminanker",
    "previous_contract_end": "Ende vorheriger Vertrag",
    "next_contract_start": "Beginn neuer Vertrag",
    "move_out_handover": "Auszugsübergabe",
    "move_in_handover": "Einzugsübergabe",
    "offsetDays": "Versatz in Tagen",
    "responsibility": "Verantwortung",
    "none": "Keine feste Zuweisung",
    "user": "Konkreter Benutzer",
    "role": "Rolle",
    "selectUser": "Aktiven Benutzer auswählen",
    "selectRole": "Rolle auswählen",
    "dependencies": "Abhängigkeiten",
    "evidenceRequirement": "Pflichtbeleg",
    "evidence_none": "Kein Beleg",
    "evidence_document_original": "Originaldokument",
    "evidence_handover_protocol": "Finalisiertes Übergabeprotokoll",
    "evidence_meter_reading": "Nachweisbarer Zählerstand",
    "readOnlyTemplate": "Diese Version ist nicht bearbeitbar.",
    "invalidStep": "Bitte alle Pflichtfelder und Zuweisungen prüfen.",
    "dependencyCycle": "Die Abhängigkeiten enthalten einen Zyklus.",
    "startTitle": "Wechselakte vorbereiten",
    "mode": "Art des Wechsels",
    "previousContract": "Vorheriger Vertrag",
    "nextContract": "Neuer Vertrag",
    "moveOutHandoverDate": "Auszugsübergabe",
    "moveInHandoverDate": "Einzugsübergabe",
    "moveOutTemplate": "Auszugsvorlage",
    "moveInTemplate": "Einzugsvorlage",
    "preview": "Vorschau erstellen",
    "confirmStart": "Wechselakte starten",
    "previewFirst": "Vor dem Start ist eine aktuelle Servervorschau erforderlich.",
    "previewHash": "Prüfsumme der Vorschau",
    "anchors": "Bestätigte Terminanker",
    "affectedSteps": "Betroffene Schritte",
    "sourceEtags": "Gelesene Quellstände",
    "previewConflicts": "Konflikte",
    "noConflicts": "Keine Konflikte gemeldet.",
    "state": "Status",
    "active": "Aktiv",
    "completed": "Abgeschlossen",
    "cancelled": "Abgebrochen",
    "open": "Offen",
    "blocked": "Blockiert",
    "in_progress": "In Bearbeitung",
    "not_applicable": "Unzutreffend",
    "dueDate": "Fällig",
    "originalDueDate": "Ursprünglich",
    "blockedBy": "Blockiert durch",
    "task": "Aufgabe",
    "createTask": "Aufgabe verknüpfen/erzeugen",
    "openTask": "Aufgabe öffnen",
    "markInProgress": "Bearbeitung starten",
    "completeStep": "Schritt erledigen",
    "notApplicable": "Als unzutreffend markieren",
    "exceptionReason": "Begründung der Ausnahme",
    "evidence": "Belege",
    "addEvidence": "Beleg verknüpfen",
    "noEvidence": "Noch kein Beleg verknüpft",
    "completedAt": "Erledigt am",
    "completedBy": "Erledigt durch",
    "completeChange": "Wechselakte abschließen",
    "cancelChange": "Wechselakte abbrechen",
    "cancelReason": "Grund des Abbruchs",
    "reanchorTitle": "Übergabetermine ändern",
    "previewReanchor": "Verschiebung prüfen",
    "applyReanchor": "Bestätigte Verschiebung anwenden",
    "changedSteps": "Offene Schritte mit Terminänderung",
    "noChanges": "Keine offenen Termine ändern sich.",
    "originalsStay": "Erledigte Schritte und ursprüngliche Fälligkeiten bleiben unverändert.",
    "selectDocument": "Dokument auswählen",
    "selectVersion": "Unveränderliche Originalfassung auswählen",
    "selectedOriginal": "Ausgewählte Originalfassung",
    "linkEvidence": "Beleg verknüpfen",
    "search": "Referenzen durchsuchen",
    "loadMore": "Weitere laden",
    "loading": "Lade …",
    "noOptions": "Keine Treffer",
    "selected": "Ausgewählt",
    "clear": "Auswahl entfernen",
    "templateState": "Vorlagenstatus",
    "stepCount": "{{count}} Schritte",
    "progress": "{{done}} von {{total}} Pflicht-/Aktivschritten erledigt",
    "missingAdapter": "Diese Aktion wartet auf den abgestimmten Backend-Adapter.",
    "pageDescription": "Versionierte Objektvorlagen und ausführbare Wechselakten mit serverautorisierten Aktionen.",
    "newTemplateDescription": "Neue Vorlage mit erster bearbeitbarer Entwurfsfassung",
    "stableKey": "Stabiler Schlüssel",
    "createTemplate": "Vorlage anlegen",
    "newDraftVersion": "Neue Entwurfsfassung",
    "selectTemplate": "Vorlage auswählen oder neu anlegen.",
    "selectChange": "Wechselakte auswählen."
  },
  "en-US": {
    "eyebrow": "Tenant turnover",
    "templatesTitle": "Templates & workflows",
    "changeTitle": "Turnover file",
    "propertyScope": "Property",
    "unitScope": "Unit",
    "objectDefault": "Property default",
    "unitOverride": "Unit override",
    "move_in": "Move-in",
    "move_out": "Move-out",
    "turnover": "Move-out & move-in",
    "version": "Version {{version}}",
    "draft": "Draft",
    "published": "Published",
    "retired": "Retired",
    "save": "Save draft",
    "publish": "Publish version",
    "working": "Saving …",
    "refresh": "Refresh",
    "close": "Close",
    "unknownTitle": "Server outcome is unclear",
    "unknownBody": "The command is kept unchanged. Only an exact replay with the same key is safe.",
    "retryExact": "Replay exactly",
    "conflictTitle": "The record changed in the meantime",
    "conflictBody": "Local input is preserved. Review the current state deliberately before continuing.",
    "reviewCurrent": "Review current state",
    "errorTitle": "Action failed",
    "addStep": "Add step",
    "removeStep": "Remove step",
    "moveUp": "Move up",
    "moveDown": "Move down",
    "stepTitle": "Step",
    "title": "Title",
    "description": "Description",
    "requirement": "Requirement",
    "required": "Required",
    "optional": "Optional",
    "anchor": "Date anchor",
    "previous_contract_end": "Previous contract end",
    "next_contract_start": "Next contract start",
    "move_out_handover": "Move-out handover",
    "move_in_handover": "Move-in handover",
    "offsetDays": "Offset in days",
    "responsibility": "Responsibility",
    "none": "No fixed assignment",
    "user": "Specific user",
    "role": "Role",
    "selectUser": "Select active user",
    "selectRole": "Select role",
    "dependencies": "Dependencies",
    "evidenceRequirement": "Required evidence",
    "evidence_none": "No evidence",
    "evidence_document_original": "Original document",
    "evidence_handover_protocol": "Finalized handover protocol",
    "evidence_meter_reading": "Verifiable meter reading",
    "readOnlyTemplate": "This version cannot be edited.",
    "invalidStep": "Check all required fields and assignments.",
    "dependencyCycle": "The dependency graph contains a cycle.",
    "startTitle": "Prepare turnover file",
    "mode": "Turnover mode",
    "previousContract": "Previous contract",
    "nextContract": "Next contract",
    "moveOutHandoverDate": "Move-out handover",
    "moveInHandoverDate": "Move-in handover",
    "moveOutTemplate": "Move-out template",
    "moveInTemplate": "Move-in template",
    "preview": "Create preview",
    "confirmStart": "Start turnover file",
    "previewFirst": "A fresh server preview is required before starting.",
    "previewHash": "Preview hash",
    "anchors": "Confirmed date anchors",
    "affectedSteps": "Affected steps",
    "sourceEtags": "Read source versions",
    "previewConflicts": "Conflicts",
    "noConflicts": "No conflicts reported.",
    "state": "State",
    "active": "Active",
    "completed": "Completed",
    "cancelled": "Cancelled",
    "open": "Open",
    "blocked": "Blocked",
    "in_progress": "In progress",
    "not_applicable": "Not applicable",
    "dueDate": "Due",
    "originalDueDate": "Original",
    "blockedBy": "Blocked by",
    "task": "Task",
    "createTask": "Link/create task",
    "openTask": "Open task",
    "markInProgress": "Start work",
    "completeStep": "Complete step",
    "notApplicable": "Mark not applicable",
    "exceptionReason": "Exception reason",
    "evidence": "Evidence",
    "addEvidence": "Link evidence",
    "noEvidence": "No evidence linked yet",
    "completedAt": "Completed at",
    "completedBy": "Completed by",
    "completeChange": "Complete turnover file",
    "cancelChange": "Cancel turnover file",
    "cancelReason": "Cancellation reason",
    "reanchorTitle": "Change handover dates",
    "previewReanchor": "Preview date shift",
    "applyReanchor": "Apply confirmed date shift",
    "changedSteps": "Open steps with changed due dates",
    "noChanges": "No open due dates change.",
    "originalsStay": "Completed steps and original due dates remain unchanged.",
    "selectDocument": "Select document",
    "selectVersion": "Select immutable original version",
    "selectedOriginal": "Selected original version",
    "linkEvidence": "Link evidence",
    "search": "Search references",
    "loadMore": "Load more",
    "loading": "Loading …",
    "noOptions": "No results",
    "selected": "Selected",
    "clear": "Clear selection",
    "templateState": "Template state",
    "stepCount": "{{count}} steps",
    "progress": "{{done}} of {{total}} required/active steps completed",
    "missingAdapter": "This action is waiting for the agreed backend adapter.",
    "pageDescription": "Versioned property workflows and executable turnover files with server-authorized actions.",
    "newTemplateDescription": "New template with its first editable draft version",
    "stableKey": "Stable key",
    "createTemplate": "Create template",
    "newDraftVersion": "New draft version",
    "selectTemplate": "Select a template or create one.",
    "selectChange": "Select a turnover file."
  },
  "es-ES": {
    "eyebrow": "Cambio de inquilino",
    "templatesTitle": "Plantillas y flujos",
    "changeTitle": "Expediente de cambio",
    "propertyScope": "Inmueble",
    "unitScope": "Unidad",
    "objectDefault": "Estándar del inmueble",
    "unitOverride": "Excepción de la unidad",
    "move_in": "Entrada",
    "move_out": "Salida",
    "turnover": "Salida y entrada",
    "version": "Versión {{version}}",
    "draft": "Borrador",
    "published": "Publicada",
    "retired": "Retirada",
    "save": "Guardar borrador",
    "publish": "Publicar versión",
    "working": "Guardando …",
    "refresh": "Actualizar",
    "close": "Cerrar",
    "unknownTitle": "El resultado del servidor no está claro",
    "unknownBody": "El comando se conserva sin cambios. Solo es seguro repetir exactamente con la misma clave.",
    "retryExact": "Repetir exactamente",
    "conflictTitle": "El registro cambió mientras tanto",
    "conflictBody": "Los datos locales se conservan. Revise conscientemente el estado actual antes de continuar.",
    "reviewCurrent": "Revisar estado actual",
    "errorTitle": "La acción falló",
    "addStep": "Añadir paso",
    "removeStep": "Eliminar paso",
    "moveUp": "Subir",
    "moveDown": "Bajar",
    "stepTitle": "Paso",
    "title": "Título",
    "description": "Descripción",
    "requirement": "Requisito",
    "required": "Obligatorio",
    "optional": "Opcional",
    "anchor": "Ancla de fecha",
    "previous_contract_end": "Fin del contrato anterior",
    "next_contract_start": "Inicio del nuevo contrato",
    "move_out_handover": "Entrega de salida",
    "move_in_handover": "Entrega de entrada",
    "offsetDays": "Desfase en días",
    "responsibility": "Responsabilidad",
    "none": "Sin asignación fija",
    "user": "Usuario concreto",
    "role": "Rol",
    "selectUser": "Seleccionar usuario activo",
    "selectRole": "Seleccionar rol",
    "dependencies": "Dependencias",
    "evidenceRequirement": "Justificante requerido",
    "evidence_none": "Sin justificante",
    "evidence_document_original": "Documento original",
    "evidence_handover_protocol": "Acta de entrega finalizada",
    "evidence_meter_reading": "Lectura de contador verificable",
    "readOnlyTemplate": "Esta versión no se puede editar.",
    "invalidStep": "Revise los campos obligatorios y las asignaciones.",
    "dependencyCycle": "El grafo de dependencias contiene un ciclo.",
    "startTitle": "Preparar expediente de cambio",
    "mode": "Tipo de cambio",
    "previousContract": "Contrato anterior",
    "nextContract": "Contrato nuevo",
    "moveOutHandoverDate": "Entrega de salida",
    "moveInHandoverDate": "Entrega de entrada",
    "moveOutTemplate": "Plantilla de salida",
    "moveInTemplate": "Plantilla de entrada",
    "preview": "Crear vista previa",
    "confirmStart": "Iniciar expediente",
    "previewFirst": "Se necesita una vista previa actual del servidor antes de iniciar.",
    "previewHash": "Hash de vista previa",
    "anchors": "Anclas de fecha confirmadas",
    "affectedSteps": "Pasos afectados",
    "sourceEtags": "Versiones de origen leídas",
    "previewConflicts": "Conflictos",
    "noConflicts": "No se notificaron conflictos.",
    "state": "Estado",
    "active": "Activo",
    "completed": "Completado",
    "cancelled": "Cancelado",
    "open": "Abierto",
    "blocked": "Bloqueado",
    "in_progress": "En curso",
    "not_applicable": "No aplicable",
    "dueDate": "Vence",
    "originalDueDate": "Original",
    "blockedBy": "Bloqueado por",
    "task": "Tarea",
    "createTask": "Vincular/crear tarea",
    "openTask": "Abrir tarea",
    "markInProgress": "Iniciar trabajo",
    "completeStep": "Completar paso",
    "notApplicable": "Marcar no aplicable",
    "exceptionReason": "Motivo de la excepción",
    "evidence": "Justificantes",
    "addEvidence": "Vincular justificante",
    "noEvidence": "Todavía no hay justificante vinculado",
    "completedAt": "Completado el",
    "completedBy": "Completado por",
    "completeChange": "Completar expediente",
    "cancelChange": "Cancelar expediente",
    "cancelReason": "Motivo de la cancelación",
    "reanchorTitle": "Cambiar fechas de entrega",
    "previewReanchor": "Previsualizar cambio",
    "applyReanchor": "Aplicar cambio confirmado",
    "changedSteps": "Pasos abiertos con nueva fecha",
    "noChanges": "No cambia ninguna fecha abierta.",
    "originalsStay": "Los pasos completados y las fechas originales permanecen sin cambios.",
    "selectDocument": "Seleccionar documento",
    "selectVersion": "Seleccionar versión original inmutable",
    "selectedOriginal": "Versión original seleccionada",
    "linkEvidence": "Vincular justificante",
    "search": "Buscar referencias",
    "loadMore": "Cargar más",
    "loading": "Cargando …",
    "noOptions": "Sin resultados",
    "selected": "Seleccionado",
    "clear": "Quitar selección",
    "templateState": "Estado de plantilla",
    "stepCount": "{{count}} pasos",
    "progress": "{{done}} de {{total}} pasos obligatorios/activos completados",
    "missingAdapter": "Esta acción espera el adaptador de backend acordado.",
    "pageDescription": "Flujos versionados por inmueble y expedientes ejecutables con acciones autorizadas por el servidor.",
    "newTemplateDescription": "Nueva plantilla con su primera versión de borrador editable",
    "stableKey": "Clave estable",
    "createTemplate": "Crear plantilla",
    "newDraftVersion": "Nueva versión de borrador",
    "selectTemplate": "Seleccione una plantilla o cree una nueva.",
    "selectChange": "Seleccione un expediente de cambio."
  }
};

export function workflowText(locale, key, params) {
  const language = workflowLanguages[locale] || workflowLanguages['de-DE'];
  let value = language[key] ?? workflowLanguages['de-DE'][key] ?? key;
  if (params && typeof value === 'string') {
    for (const [name, replacement] of Object.entries(params)) {
      value = value.replaceAll(`{{${name}}}`, String(replacement));
    }
  }
  return value;
}
