const de = {
  title: 'Widerspruchsakten', status: 'Prüfstand', open: 'Offen', in_review: 'In Prüfung', withdrawn: 'Zurückgenommen', closed: 'Abgeschlossen',
  opened: 'Eröffnet', note: 'Notiz', reopened: 'Wiederaufnahme', correction: 'Berichtigung', correction_link: 'Korrektur verknüpft',
  tenant_statement: 'Einzelabrechnung', property_review: 'Objektprüfung', loading: 'Wird geladen …', retry: 'Erneut laden',
  invalidDisputeResponse: 'Die Aktenantwort konnte nicht geprüft werden. Bitte den aktuellen Stand erneut laden.',
  unavailable: 'Der Zugriff wurde geändert oder die Akte ist nicht verfügbar.', emptyCases: 'Keine passenden Akten auf dieser Seite.',
  previous: 'Vorherige Seite', next: 'Nächste Seite', page: 'Seite', case: 'Akte', revision: 'Revision', created: 'Erfasst am',
  actualDate: 'Tatsächliches Datum', author: 'Erfasst von', reason: 'Grund / Notiz', history: 'Chronik', original: 'Beanstandete Originalfassung',
  originalEvent: 'Originalereignis', showOriginal: 'Originalereignis öffnen', close: 'Schließen', download: 'Original herunterladen',
  evidence: 'Originalanlagen', noEvidence: 'Keine Originalanlagen an diesem Ereignis.', positions: 'Beanstandete Originalpositionen',
  position: 'Position', description: 'Beschreibung', amount: 'Originalbetrag', total: 'Kostenanteil', advance: 'Bezahlte Vorauszahlung', balance: 'Saldo',
  partyUnknown: 'Diese Akte liefert keinen belegten damaligen Personenbezug. Aktuelle Vertragsdaten werden nicht als historische Identität ergänzt.',
  propertyParty: 'Objektprüfung ohne Mietparteibezug.', correctionTarget: 'Berichtigt Originalereignis', statementLink: 'Verknüpfte Korrekturabrechnung',
  noHistory: 'Keine Ereignisse auf dieser Seite.', financial: 'Aktenaktionen ändern keine Forderung, Erstattung oder Zustellung. Finanzfolgen bleiben gesondert zu bestätigen.',
  legacy: 'Altstatus ohne vollständige Widerspruchsakte. Daraus werden kein Grund, Eingang oder Originalbeleg ergänzt.',
  all: 'Alle Prüfstände', count: 'Akten insgesamt', openCount: 'Offene Akten', refresh: 'Aktuellen Stand laden',
  technical: 'Originalkennungen und Prüfsummen', snapshotHash: 'Abrechnungsoriginalhash', originalHash: 'Aktenoriginalhash',
  originalJson: 'Weitere unveränderte Originalangaben', sourceStatement: 'Originalabrechnung', originalUnit: 'Originaleinheit', originalContract: 'Originalvertrag',
  bytes: 'Byte', received: 'Tatsächlicher Eingang', observed: 'Tatsächliches Beobachtungsdatum', preview: 'Vorschau prüfen', confirm: 'Unverändert bestätigen',
  review: 'Geprüfte Vorschau', edit: 'Eingaben bearbeiten', unknown: 'Die Speicherantwort fehlt. Dieser vorbereitete Befehl bleibt unverändert erhalten.',
  exactRetry: 'Denselben Befehl erneut senden', saved: 'Aktion bestätigt', conflict: 'Der geprüfte Stand wurde geändert. Ihre Eingaben bleiben erhalten.',
  newCase: 'Neue Akte erfassen', newEvent: 'Folgeereignis erfassen', chooseStatement: 'Finalisierte Einzelabrechnung', chooseType: 'Vorgangstyp',
};
const en = {
  ...de, title: 'Objection files', status: 'Review status', open: 'Open', in_review: 'Under review', withdrawn: 'Withdrawn', closed: 'Closed',
  opened: 'Opened', note: 'Note', reopened: 'Reopened', correction: 'Correction', correction_link: 'Linked corrected statement',
  tenant_statement: 'Individual statement', property_review: 'Property review', loading: 'Loading …', retry: 'Try again',
  invalidDisputeResponse: 'The file response could not be verified. Please reload the current record.', unavailable: 'Access has changed or this file is unavailable.',
  emptyCases: 'No matching files on this page.', previous: 'Previous page', next: 'Next page', page: 'Page', case: 'File', revision: 'Revision',
  created: 'Recorded on', actualDate: 'Actual date', author: 'Recorded by', reason: 'Reason / note', history: 'History', original: 'Disputed original statement',
  originalEvent: 'Original event', showOriginal: 'Open original event', close: 'Close', download: 'Download original', evidence: 'Original attachments',
  noEvidence: 'No original attachments for this event.', positions: 'Disputed original items', position: 'Item', description: 'Description', amount: 'Original amount',
  total: 'Allocated cost', advance: 'Paid advance', balance: 'Balance',
  partyUnknown: 'This file does not establish the historical person. Current contract data is not added as historical identity.',
  propertyParty: 'Property review without a tenant reference.', correctionTarget: 'Corrects original event', statementLink: 'Linked corrected statement',
  noHistory: 'No events on this page.', financial: 'File actions do not change receivables, refunds or delivery. Financial effects require separate confirmation.',
  legacy: 'Legacy status without a complete objection file. No reason, receipt date or original evidence is inferred.',
  all: 'All review statuses', count: 'Total files', openCount: 'Open files', refresh: 'Reload current record', technical: 'Original identifiers and checksums',
  snapshotHash: 'Statement original hash', originalHash: 'File original hash', originalJson: 'Other unchanged original fields',
  sourceStatement: 'Original statement', originalUnit: 'Original unit', originalContract: 'Original contract', bytes: 'bytes', received: 'Actual receipt date',
  observed: 'Actual observation date', preview: 'Review preview', confirm: 'Confirm unchanged', review: 'Reviewed preview', edit: 'Edit inputs',
  unknown: 'The save response is missing. This prepared command is preserved unchanged.', exactRetry: 'Resend the same command', saved: 'Action confirmed',
  conflict: 'The reviewed record has changed. Your inputs are preserved.', newCase: 'Record new file', newEvent: 'Record next event',
  chooseStatement: 'Finalized individual statement', chooseType: 'File type',
};
const es = {
  ...en, title: 'Expedientes de reclamación', status: 'Estado de revisión', open: 'Abierto', in_review: 'En revisión', withdrawn: 'Retirado', closed: 'Cerrado',
  opened: 'Apertura', note: 'Nota', reopened: 'Reapertura', correction: 'Rectificación', correction_link: 'Liquidación rectificada vinculada',
  tenant_statement: 'Liquidación individual', property_review: 'Revisión del inmueble', loading: 'Cargando …', retry: 'Reintentar',
  invalidDisputeResponse: 'No se pudo verificar la respuesta del expediente. Vuelva a cargar los datos actuales.', unavailable: 'El acceso ha cambiado o el expediente no está disponible.',
  emptyCases: 'No hay expedientes coincidentes en esta página.', previous: 'Página anterior', next: 'Página siguiente', page: 'Página', case: 'Expediente',
  revision: 'Revisión', created: 'Registrado el', actualDate: 'Fecha real', author: 'Registrado por', reason: 'Motivo / nota', history: 'Historial',
  original: 'Liquidación original reclamada', originalEvent: 'Evento original', showOriginal: 'Abrir evento original', close: 'Cerrar', download: 'Descargar original',
  evidence: 'Anexos originales', noEvidence: 'Este evento no tiene anexos originales.', positions: 'Partidas originales reclamadas', position: 'Partida',
  description: 'Descripción', amount: 'Importe original', total: 'Coste asignado', advance: 'Anticipo pagado', balance: 'Saldo',
  partyUnknown: 'Este expediente no acredita la identidad histórica. Los datos actuales del contrato no se añaden como identidad anterior.',
  propertyParty: 'Revisión del inmueble sin referencia a un inquilino.', correctionTarget: 'Rectifica el evento original', statementLink: 'Liquidación rectificada vinculada',
  noHistory: 'No hay eventos en esta página.', financial: 'Las acciones del expediente no cambian cobros, reembolsos ni entregas. Los efectos financieros requieren confirmación separada.',
  legacy: 'Estado antiguo sin expediente completo. No se deducen motivo, fecha de entrada ni anexos originales.',
  all: 'Todos los estados', count: 'Total de expedientes', openCount: 'Expedientes abiertos', refresh: 'Cargar datos actuales',
  technical: 'Identificadores originales y sumas de comprobación', snapshotHash: 'Hash de la liquidación original', originalHash: 'Hash del expediente original',
  originalJson: 'Otros datos originales sin modificar', sourceStatement: 'Liquidación original', originalUnit: 'Unidad original', originalContract: 'Contrato original',
  bytes: 'bytes', received: 'Fecha real de entrada', observed: 'Fecha real de observación', preview: 'Revisar vista previa', confirm: 'Confirmar sin cambios',
  review: 'Vista previa revisada', edit: 'Editar datos', unknown: 'Falta la respuesta del guardado. El comando preparado se conserva sin cambios.',
  exactRetry: 'Reenviar el mismo comando', saved: 'Acción confirmada', conflict: 'Los datos revisados han cambiado. Sus entradas se conservan.',
  newCase: 'Registrar expediente', newEvent: 'Registrar evento', chooseStatement: 'Liquidación individual finalizada', chooseType: 'Tipo de expediente',
};
export const disputeLanguages = { 'de-DE': de, 'en-US': en, 'es-ES': es };
export const disputeText = (locale, key) => (disputeLanguages[locale] || de)[key] || de[key] || key;
