const messages = {
  de: {
    loading: 'Einheitenakte wird geladen …', error: 'Die Einheitenakte konnte nicht geladen werden.',
    retry: 'Erneut laden', restart: 'Erste Seiten laden', back: 'Zur Einheitenliste', refresh: 'Aktualisieren',
    facts: 'Eckdaten', type: 'Art', floor: 'Etage', area: 'Fläche', rooms: 'Zimmer', people: 'Personenzahl',
    features: 'Ausstattung', rent: 'Kaltmiete', service: 'Nebenkostenvorauszahlung', heating: 'Heizkostenvorauszahlung',
    active: 'Aktive Mietverträge', activeBasis: 'Verträge mit dem gespeicherten Status „Aktiv“.',
    noActive: 'Kein Vertrag mit dem Status „Aktiv“ vorhanden.',
    multiple: 'Mehrere aktive Verträge sind hinterlegt. Bitte die Vertragszeiträume prüfen.',
    history: 'Vertragshistorie', emptyHistory: 'Keine Verträge für diese Einheit vorhanden.',
    tenant: 'Mietpartei', start: 'Beginn', end: 'Ende', indefinite: 'Unbefristet', deposit: 'Kaution',
    insurance: 'Einheitsspezifische Versicherungen', emptyInsurance: 'Keine einheitsspezifischen Versicherungen vorhanden.',
    previous: 'Vorherige Seite', next: 'Nächste Seite', page: 'Seite', emptyPage: 'Auf dieser Seite sind aktuell keine Einträge vorhanden.', amountBasis: 'Gespeicherte Monatswerte der Einheit.',
    unavailable: 'Die Einheit ist nicht verfügbar oder der Zugriff wurde geändert.',
    invalid: 'Die Antwort passt nicht zur angefragten Einheitenakte. Bitte erneut laden.',
    unitStatus: 'Status der Einheit',
    types: { apartment: 'Wohnung', commercial: 'Gewerbe', parking: 'Stellplatz', basement: 'Keller', other: 'Sonstiges' },
    statuses: { vacant: 'Leer', occupied: 'Vermietet', rented: 'Vermietet', reserved: 'Reserviert', expired: 'Abgelaufen' },
    insuranceTypes: { building: 'Gebäudeversicherung', liability: 'Haftpflicht', contents: 'Hausrat', legal: 'Rechtsschutz', rent_loss: 'Mietausfall', other: 'Sonstige' },
  },
  en: {
    loading: 'Loading unit workspace …', error: 'The unit workspace could not be loaded.',
    retry: 'Reload', restart: 'Load first pages', back: 'Back to units', refresh: 'Refresh',
    facts: 'Unit details', type: 'Type', floor: 'Floor', area: 'Area', rooms: 'Rooms', people: 'Occupants',
    features: 'Features', rent: 'Base rent', service: 'Service charge advance', heating: 'Heating advance',
    active: 'Active leases', activeBasis: 'Leases with the recorded status “Active”.',
    noActive: 'No lease with the status “Active” is recorded.',
    multiple: 'Several active leases are recorded. Please check their periods.',
    history: 'Lease history', emptyHistory: 'No leases are recorded for this unit.',
    tenant: 'Tenant', start: 'Start', end: 'End', indefinite: 'Open-ended', deposit: 'Deposit',
    insurance: 'Unit-specific insurance', emptyInsurance: 'No unit-specific insurance is recorded.',
    previous: 'Previous page', next: 'Next page', page: 'Page', emptyPage: 'There are currently no entries on this page.', amountBasis: 'Recorded monthly unit amounts.',
    unavailable: 'The unit is unavailable or access has changed.',
    invalid: 'The response does not match the requested unit. Please reload.',
    unitStatus: 'Recorded unit status',
    types: { apartment: 'Apartment', commercial: 'Commercial', parking: 'Parking space', basement: 'Basement', other: 'Other' },
    statuses: { vacant: 'Vacant', occupied: 'Occupied', rented: 'Rented', reserved: 'Reserved', expired: 'Expired' },
    insuranceTypes: { building: 'Building insurance', liability: 'Liability', contents: 'Contents', legal: 'Legal expenses', rent_loss: 'Rent loss', other: 'Other' },
  },
  es: {
    loading: 'Cargando la ficha de la unidad …', error: 'No se pudo cargar la ficha de la unidad.',
    retry: 'Volver a cargar', restart: 'Cargar las primeras páginas', back: 'Volver a las unidades', refresh: 'Actualizar',
    facts: 'Datos de la unidad', type: 'Tipo', floor: 'Planta', area: 'Superficie', rooms: 'Habitaciones', people: 'Ocupantes',
    features: 'Equipamiento', rent: 'Alquiler base', service: 'Anticipo de gastos', heating: 'Anticipo de calefacción',
    active: 'Contratos activos', activeBasis: 'Contratos con el estado registrado «Activo».',
    noActive: 'No hay ningún contrato con el estado «Activo».',
    multiple: 'Hay varios contratos activos. Compruebe sus períodos.',
    history: 'Historial de contratos', emptyHistory: 'No hay contratos registrados para esta unidad.',
    tenant: 'Inquilino', start: 'Inicio', end: 'Fin', indefinite: 'Indefinido', deposit: 'Fianza',
    insurance: 'Seguros específicos de la unidad', emptyInsurance: 'No hay seguros específicos de esta unidad.',
    previous: 'Página anterior', next: 'Página siguiente', page: 'Página', emptyPage: 'Actualmente no hay registros en esta página.', amountBasis: 'Importes mensuales registrados de la unidad.',
    unavailable: 'La unidad no está disponible o los permisos han cambiado.',
    invalid: 'La respuesta no corresponde a la unidad solicitada. Vuelva a cargarla.',
    unitStatus: 'Estado registrado de la unidad',
    types: { apartment: 'Vivienda', commercial: 'Local comercial', parking: 'Plaza de aparcamiento', basement: 'Sótano', other: 'Otro' },
    statuses: { vacant: 'Libre', occupied: 'Alquilada', rented: 'Alquilada', reserved: 'Reservada', expired: 'Vencido' },
    insuranceTypes: { building: 'Seguro del edificio', liability: 'Responsabilidad civil', contents: 'Contenido', legal: 'Defensa jurídica', rent_loss: 'Pérdida de alquiler', other: 'Otro' },
  },
};

export const unitWorkspaceText = locale => messages[locale?.split('-')[0]] || messages.de;
