const COPY = {
  'de-DE': {
    back: 'Zurück zum Formular', download: 'PDF herunterladen', previewPdfTitle: 'Vorschau der Wohnungsgeberbestätigung',
    originalPdfTitle: 'Gespeicherte Wohnungsgeberbestätigung', discardTitle: 'Ungespeicherte Angaben verwerfen?',
    discardConfirm: 'Verwerfen und schließen', keepEditing: 'Weiter bearbeiten',
    readOnly: 'Nur Lesezugriff: gespeicherte Bestätigungen ansehen; Freigeben ist Ihrer Rolle nicht erlaubt.',
    action: 'Wohnungsgeberbestätigung',
    title: 'Wohnungsgeberbestätigung', eyebrow: 'Einzug & Meldung',
    openFromContract: 'Wohnungsgeberbestätigung', openFromMoveIn: 'Bestätigung vorbereiten',
    moveInEntryHint: 'Für den neuen Mietvertrag vorbereiten. Übergabe und Vertragsbeginn sind nur Referenzen; der tatsächliche Einzug wird im Formular bewusst eingetragen.',
    loading: 'Lade aktuelle Vertragsdaten …', loadFailed: 'Die aktuellen Vertragsdaten konnten nicht geladen werden.',
    accessLost: 'Die Wohnungsgeberbestätigung ist in diesem Zugriff nicht verfügbar.', close: 'Schließen',
    discardPrompt: 'Ungespeicherte Angaben oder eine ungeklärte Freigabe würden verworfen. Wirklich schließen?',
    dwelling: 'Wohnung', provider: 'Wohnungsgeber', owner: 'Eigentümer', persons: 'Einziehende Personen', issue: 'Ausstellung',
    history: 'Gespeicherte Bestätigungen', property: 'Objekt', unit: 'Einheit', contract: 'Mietvertrag',
    contractStart: 'Vertragsbeginn', handoverReference: 'Übergabe als Referenz',
    actualMoveIn: 'Tatsächlicher Einzug',
    actualMoveInHint: 'Dieses Datum wird bewusst eingegeben und nicht aus Vertragsbeginn oder Übergabe übernommen.',
    issueDate: 'Ausstellungsdatum', dwellingAddress: 'Anschrift der Wohnung', dwellingLabel: 'Wohnungsbezeichnung',
    providerName: 'Name des Wohnungsgebers', providerAddress: 'Anschrift des Wohnungsgebers',
    ownerRelation: 'Eigentumsverhältnis', ownerUnknown: 'Bitte auswählen',
    ownerSame: 'Wohnungsgeber ist Eigentümer', ownerDifferent: 'Eigentümer ist eine andere Person / Stelle',
    ownerName: 'Name des Eigentümers', issuerName: 'Ausstellende Person', issuerRole: 'Rolle der ausstellenden Person',
    role_housing_provider: 'Wohnungsgeber', role_authorized_person: 'Beauftragte Person',
    occupant: 'Vollständiger Name', addPerson: 'Person hinzufügen', removePerson: 'Person entfernen',
    mainTenantSuggestion: 'Hauptmieter als Vorschlag', addSuggestion: 'Vorschlag hinzufügen',
    sourceSuggestion: 'Aus Vertrags-/Objektdaten übernehmen', preview: 'Vorschau prüfen',
    previewReady: 'Vorläufige Vorschau geprüft', previewInvalidated: 'Die Vorschau wurde wegen einer Änderung verworfen.',
    confirmOccupancy: 'Ich bestätige, dass die eingetragenen Personen tatsächlich in die Wohnung einziehen.',
    confirmActualMoveIn: 'Ich bestätige, dass das angegebene Einzugsdatum der tatsächliche Einzug ist.',
    confirmAuthority: 'Ich bestätige, dass die ausstellende Person zur Ausstellung dieser Bestätigung befugt ist.',
    publish: 'Freigeben und Original speichern',
    published: 'Die freigegebene Fassung wurde als unveränderliches Original gespeichert.',
    noAuthorityClaim: 'Das PDF wird ausgedruckt und von Hand unterschrieben. Freigegebene Fassungen bleiben unverändert im Dokumentarchiv.',
    openPreviewPdf: 'PDF-Vorschau öffnen',
    unknownTitle: 'Verbindung unterbrochen',
    unknownBody: 'Ob die Freigabe angekommen ist, ist unklar. Die exakt vorbereitete Freigabe bleibt unverändert erhalten.',
    retryExact: 'Unverändert erneut senden', conflictTitle: 'Quelldaten haben sich geändert',
    conflictBody: 'Ihre Eingaben bleiben erhalten. Bitte aktuelle Vertragsdaten bewusst neu prüfen.',
    reloadSource: 'Aktuelle Quellen neu prüfen', errorTitle: 'Aktion fehlgeschlagen',
    correction: 'Korrektur erstellen', correctionOf: 'Korrektur zu einer früheren Bestätigung',
    openPdf: 'PDF öffnen', loadMore: 'Weitere laden', noHistory: 'Noch keine gespeicherte Wohnungsgeberbestätigung.',
    suggestedAddress: 'Adressvorschlag', suggestedProvider: 'Wohnungsgeber-Vorschlag',
    suggestedOwner: 'Eigentümer-Vorschlag', warnings: 'Hinweise',
    personsCount: '{{count}} Personen in dieser Vorschau', requiredFields: 'Bitte alle erforderlichen Angaben prüfen.',
    dirtyStatus: 'Ungespeicherte Änderungen', correctionStatus: 'Korrektur wird vorbereitet',
  },
  'en-US': {
    back: 'Back to the form', download: 'Download PDF', previewPdfTitle: 'Preview of the housing provider confirmation',
    originalPdfTitle: 'Saved housing provider confirmation', discardTitle: 'Discard unsaved details?',
    discardConfirm: 'Discard and close', keepEditing: 'Keep editing',
    readOnly: 'Read-only access: view saved confirmations; your role may not release them.',
    action: 'Housing provider confirmation',
    title: 'Housing provider confirmation', eyebrow: 'Move-in & registration',
    openFromContract: 'Housing provider confirmation', openFromMoveIn: 'Prepare confirmation',
    moveInEntryHint: 'Prepare it for the new lease. Handover and contract start are references only; the actual move-in is entered deliberately in the form.',
    loading: 'Loading current contract data …', loadFailed: 'Current contract data could not be loaded.',
    accessLost: 'The housing confirmation is not available with this access.', close: 'Close',
    discardPrompt: 'Unsaved details or an unresolved release would be discarded. Close anyway?',
    dwelling: 'Dwelling', provider: 'Housing provider', owner: 'Owner', persons: 'People moving in', issue: 'Issue details',
    history: 'Saved confirmations', property: 'Property', unit: 'Unit', contract: 'Lease',
    contractStart: 'Contract start', handoverReference: 'Handover reference',
    actualMoveIn: 'Actual move-in', actualMoveInHint: 'Enter this date deliberately; it is not copied from contract start or handover.',
    issueDate: 'Issue date', dwellingAddress: 'Dwelling address', dwellingLabel: 'Dwelling designation',
    providerName: 'Housing provider name', providerAddress: 'Housing provider address',
    ownerRelation: 'Ownership relationship', ownerUnknown: 'Please choose',
    ownerSame: 'Housing provider is the owner', ownerDifferent: 'Owner is another person / organization',
    ownerName: 'Owner name', issuerName: 'Issuing person', issuerRole: 'Role of issuing person',
    role_housing_provider: 'Housing provider', role_authorized_person: 'Authorized person',
    occupant: 'Full name', addPerson: 'Add person', removePerson: 'Remove person',
    mainTenantSuggestion: 'Main tenant suggestion', addSuggestion: 'Add suggestion',
    sourceSuggestion: 'Use contract/property suggestion', preview: 'Review preview',
    previewReady: 'Preliminary preview reviewed', previewInvalidated: 'The preview was discarded because an input changed.',
    confirmOccupancy: 'I confirm that the listed people are actually moving into the dwelling.',
    confirmActualMoveIn: 'I confirm that the stated move-in date is the actual move-in date.',
    confirmAuthority: 'I confirm that the issuing person is authorized to issue this confirmation.',
    publish: 'Release and save original', published: 'The released version was stored as an immutable original.',
    noAuthorityClaim: 'Provide the PDF for signature. Released versions remain in the document archive.',
    openPreviewPdf: 'Open PDF preview',
    unknownTitle: 'Connection interrupted', unknownBody: 'It is unclear whether the release arrived. The exact prepared release remains unchanged.',
    retryExact: 'Send unchanged again', conflictTitle: 'Source data changed',
    conflictBody: 'Your input is preserved. Deliberately review the current contract data before continuing.',
    reloadSource: 'Review current sources', errorTitle: 'Action failed', correction: 'Create correction',
    correctionOf: 'Correction of an earlier confirmation', openPdf: 'Open PDF', loadMore: 'Load more',
    noHistory: 'No saved housing confirmation yet.', suggestedAddress: 'Address suggestion',
    suggestedProvider: 'Housing provider suggestion', suggestedOwner: 'Owner suggestion',
    warnings: 'Notes', personsCount: '{{count}} people in this preview',
    requiredFields: 'Please review all required details.', dirtyStatus: 'Unsaved changes', correctionStatus: 'Correction is being prepared',
  },
  'es-ES': {
    back: 'Volver al formulario', download: 'Descargar PDF', previewPdfTitle: 'Vista previa de la confirmación',
    originalPdfTitle: 'Confirmación guardada', discardTitle: '¿Descartar los datos sin guardar?',
    discardConfirm: 'Descartar y cerrar', keepEditing: 'Seguir editando',
    readOnly: 'Solo lectura: ver confirmaciones guardadas; su rol no puede liberarlas.',
    action: 'Confirmación del arrendador',
    title: 'Confirmación del arrendador', eyebrow: 'Entrada y empadronamiento',
    openFromContract: 'Confirmación del arrendador', openFromMoveIn: 'Preparar confirmación',
    moveInEntryHint: 'Prepárela para el nuevo contrato. La entrega y el inicio del contrato son solo referencias; la entrada real se indica de forma consciente en el formulario.',
    loading: 'Cargando datos actuales del contrato …', loadFailed: 'No se pudieron cargar los datos actuales del contrato.',
    accessLost: 'La confirmación no está disponible con este acceso.', close: 'Cerrar',
    discardPrompt: 'Se descartarían datos sin guardar o una liberación no aclarada. ¿Cerrar de todos modos?',
    dwelling: 'Vivienda', provider: 'Arrendador', owner: 'Propietario', persons: 'Personas que entran', issue: 'Emisión',
    history: 'Confirmaciones guardadas', property: 'Inmueble', unit: 'Unidad', contract: 'Contrato',
    contractStart: 'Inicio del contrato', handoverReference: 'Entrega como referencia',
    actualMoveIn: 'Entrada real', actualMoveInHint: 'Introduzca esta fecha de forma consciente; no se copia del contrato ni de la entrega.',
    issueDate: 'Fecha de emisión', dwellingAddress: 'Dirección de la vivienda', dwellingLabel: 'Identificación de la vivienda',
    providerName: 'Nombre del arrendador', providerAddress: 'Dirección del arrendador',
    ownerRelation: 'Relación con la propiedad', ownerUnknown: 'Seleccione',
    ownerSame: 'El arrendador es el propietario', ownerDifferent: 'El propietario es otra persona / entidad',
    ownerName: 'Nombre del propietario', issuerName: 'Persona que emite', issuerRole: 'Rol de la persona que emite',
    role_housing_provider: 'Arrendador', role_authorized_person: 'Persona autorizada',
    occupant: 'Nombre completo', addPerson: 'Añadir persona', removePerson: 'Quitar persona',
    mainTenantSuggestion: 'Sugerencia de inquilino principal', addSuggestion: 'Añadir sugerencia',
    sourceSuggestion: 'Usar sugerencia del contrato/inmueble', preview: 'Revisar vista previa',
    previewReady: 'Vista previa provisional revisada', previewInvalidated: 'La vista previa se descartó por un cambio.',
    confirmOccupancy: 'Confirmo que las personas indicadas realmente entran en la vivienda.',
    confirmActualMoveIn: 'Confirmo que la fecha indicada es la fecha real de entrada.',
    confirmAuthority: 'Confirmo que la persona emisora está autorizada a emitir esta confirmación.',
    publish: 'Liberar y guardar original', published: 'La versión liberada se guardó como original inmutable.',
    noAuthorityClaim: 'Prepare el PDF para firmarlo. Las versiones liberadas se conservan en el archivo documental.',
    openPreviewPdf: 'Abrir vista previa PDF',
    unknownTitle: 'Conexión interrumpida', unknownBody: 'No está claro si la liberación llegó. La liberación preparada se conserva exactamente.',
    retryExact: 'Enviar de nuevo sin cambios', conflictTitle: 'Los datos fuente cambiaron',
    conflictBody: 'Sus datos se conservan. Revise conscientemente el contrato actual antes de continuar.',
    reloadSource: 'Revisar fuentes actuales', errorTitle: 'La acción falló', correction: 'Crear corrección',
    correctionOf: 'Corrección de una confirmación anterior', openPdf: 'Abrir PDF', loadMore: 'Cargar más',
    noHistory: 'Aún no hay una confirmación guardada.', suggestedAddress: 'Sugerencia de dirección',
    suggestedProvider: 'Sugerencia de arrendador', suggestedOwner: 'Sugerencia de propietario',
    warnings: 'Avisos', personsCount: '{{count}} personas en esta vista previa',
    requiredFields: 'Revise todos los datos obligatorios.', dirtyStatus: 'Cambios sin guardar', correctionStatus: 'Se está preparando una corrección',
  },
};

export function housingText(locale = 'de-DE', key, params = {}) {
  const table = COPY[locale] || COPY['de-DE'];
  let value = table[key] ?? COPY['de-DE'][key] ?? key;
  for (const [name, replacement] of Object.entries(params)) {
    value = value.replaceAll(`{{${name}}}`, String(replacement));
  }
  return value;
}
