const TEXT = {
  'de-DE': {
    title: 'Mieterwechsel', templates: 'Vorlagen', changes: 'Wechselakten', createTemplate: 'Vorlage anlegen',
    createChange: 'Wechselakte starten', property: 'Immobilie', unit: 'Einheit', direction: 'Richtung',
    move_in: 'Einzug', move_out: 'Auszug', turnover: 'Aus- und Einzug', versions: 'Versionen',
    published: 'Veröffentlicht', draft: 'Entwurf', retired: 'Ausgemustert', active: 'Aktiv',
    completed: 'Abgeschlossen', cancelled: 'Abgebrochen', loadMore: 'Weitere laden', empty: 'Noch keine Einträge.',
    previousContract: 'Bisheriger Vertrag', nextContract: 'Neuer Vertrag', outDate: 'Auszugsübergabe',
    inDate: 'Einzugsübergabe', preview: 'Vorschau prüfen', confirmStart: 'Mit dieser Vorschau starten',
    previewChanged: 'Vorschau ist veraltet. Bitte neu prüfen.', steps: 'Checkliste', blocked: 'Blockiert',
    open: 'Offen', in_progress: 'In Bearbeitung', not_applicable: 'Unzutreffend', required: 'Pflicht',
    optional: 'Optional', due: 'Fällig', originalDue: 'ursprünglich', assignee: 'Verantwortung',
    retryExact: 'Exakten Befehl erneut senden', unknown: 'Serverergebnis unklar. Derselbe Befehl kann sicher erneut geprüft werden.',
    review: 'Stand hat sich geändert. Bitte aktuellen Stand bewusst neu laden.', reload: 'Neu laden',
    completeChange: 'Akte abschließen', completionBlocked: 'Abschluss ist noch blockiert.', templateHint: 'Einzug und Auszug werden getrennt versioniert.',
    state: 'Status', noAction: 'Keine Aktion verfügbar', evidence: 'Belege', task: 'Aufgabe',
    anchors: { previous_contract_end: 'Ende bisheriger Vertrag', next_contract_start: 'Beginn neuer Vertrag',
      move_out_handover: 'Auszugsübergabe', move_in_handover: 'Einzugsübergabe' },
  },
  'en-US': {
    title: 'Tenancy changes', templates: 'Templates', changes: 'Change files', createTemplate: 'Create template',
    createChange: 'Start tenancy change', property: 'Property', unit: 'Unit', direction: 'Direction',
    move_in: 'Move-in', move_out: 'Move-out', turnover: 'Move-out and move-in', versions: 'Versions',
    published: 'Published', draft: 'Draft', retired: 'Retired', active: 'Active', completed: 'Completed',
    cancelled: 'Cancelled', loadMore: 'Load more', empty: 'No entries yet.', previousContract: 'Previous contract',
    nextContract: 'Next contract', outDate: 'Move-out handover', inDate: 'Move-in handover', preview: 'Review preview',
    confirmStart: 'Start with this preview', previewChanged: 'Preview is stale. Review it again.', steps: 'Checklist',
    blocked: 'Blocked', open: 'Open', in_progress: 'In progress', not_applicable: 'Not applicable',
    required: 'Required', optional: 'Optional', due: 'Due', originalDue: 'original', assignee: 'Assignee',
    retryExact: 'Retry exact command', unknown: 'Server outcome is unknown. The same command can be checked safely.',
    review: 'The record changed. Reload and review it deliberately.', reload: 'Reload', completeChange: 'Complete file',
    completionBlocked: 'Completion is still blocked.', templateHint: 'Move-in and move-out are versioned separately.',
    state: 'State', noAction: 'No action available', evidence: 'Evidence', task: 'Task',
    anchors: { previous_contract_end: 'Previous contract end', next_contract_start: 'Next contract start',
      move_out_handover: 'Move-out handover', move_in_handover: 'Move-in handover' },
  },
  'es-ES': {
    title: 'Cambios de inquilino', templates: 'Plantillas', changes: 'Expedientes', createTemplate: 'Crear plantilla',
    createChange: 'Iniciar cambio', property: 'Inmueble', unit: 'Unidad', direction: 'Dirección',
    move_in: 'Entrada', move_out: 'Salida', turnover: 'Salida y entrada', versions: 'Versiones',
    published: 'Publicada', draft: 'Borrador', retired: 'Retirada', active: 'Activa', completed: 'Completada',
    cancelled: 'Cancelada', loadMore: 'Cargar más', empty: 'Todavía no hay elementos.', previousContract: 'Contrato anterior',
    nextContract: 'Contrato nuevo', outDate: 'Entrega de salida', inDate: 'Entrega de entrada', preview: 'Revisar vista previa',
    confirmStart: 'Iniciar con esta vista previa', previewChanged: 'La vista previa está desactualizada. Revísela de nuevo.',
    steps: 'Lista de control', blocked: 'Bloqueado', open: 'Abierto', in_progress: 'En curso',
    not_applicable: 'No aplicable', required: 'Obligatorio', optional: 'Opcional', due: 'Vence',
    originalDue: 'original', assignee: 'Responsable', retryExact: 'Reenviar el mismo comando',
    unknown: 'El resultado del servidor no está claro. Puede comprobarse con el mismo comando.',
    review: 'El registro cambió. Recargue y revíselo conscientemente.', reload: 'Recargar',
    completeChange: 'Completar expediente', completionBlocked: 'El cierre sigue bloqueado.',
    templateHint: 'Entrada y salida se versionan por separado.', state: 'Estado', noAction: 'Sin acción disponible',
    evidence: 'Pruebas', task: 'Tarea',
    anchors: { previous_contract_end: 'Fin del contrato anterior', next_contract_start: 'Inicio del contrato nuevo',
      move_out_handover: 'Entrega de salida', move_in_handover: 'Entrega de entrada' },
  },
};

export function workflowText(locale) {
  return TEXT[locale] || TEXT['de-DE'];
}
