// Texts of the handover protocol screens (de/en/es); the PDF itself is German.
export const COPY = {
  'de-DE': {
    action: 'Übergabeprotokolle', title: 'Übergabeprotokoll', eyebrow: 'Mieterwechsel', listTitle: 'Übergabeprotokolle',
    close: 'Schließen', back: 'Zurück zum Protokoll', loading: 'Wird geladen …',
    loadFailed: 'Das Übergabeprotokoll konnte nicht geladen werden.', retry: 'Erneut versuchen',
    readOnly: 'Nur Lesezugriff: Ihre Rolle darf Übergabeprotokolle nicht ändern.',
    type_move_in: 'Einzug', type_move_out: 'Auszug',
    state_draft: 'Entwurf', state_correction: 'Korrektur (Entwurf)', state_finalized: 'Abgeschlossen',
    state_superseded: 'Durch Korrektur ersetzt',
    legacyFinalized: 'Früher von Hand als „abgeschlossen“ markiert – es gibt kein archiviertes Original. Bitte prüfen und abschließen.',
    contract: 'Vertrag', unit: 'Einheit', property: 'Objekt', tenant: 'Mieter', date: 'Datum', kind: 'Art', status: 'Status',
    general: 'Allgemein', protocolDate: 'Übergabedatum', tenantPresent: 'Mieter anwesend',
    landlordPresent: 'Vermieter bzw. Beauftragte anwesend', overallCondition: 'Gesamtzustand',
    notAssessed: 'nicht bewertet', tenantSigner: 'Unterschrift Mieter (Name)',
    landlordSigner: 'Unterschrift Vermieter / Beauftragte (Name)', notes: 'Bemerkungen',
    condition_good: 'gut', condition_fair: 'befriedigend', condition_poor: 'mangelhaft',
    rooms: 'Räume', roomName: 'Raum', condition: 'Zustand', addRoom: 'Raum hinzufügen', removeRoom: 'Raum entfernen',
    noRooms: 'Noch keine Räume erfasst.',
    defects: 'Mängel', defectRoom: 'Raum', generalRoom: 'allgemein', description: 'Beschreibung',
    responsible: 'Verantwortlich', responsible_tenant: 'Mieter', responsible_landlord: 'Vermieter',
    responsible_open: 'offen / zu klären', remedy: 'Vereinbarung', dueDate: 'Frist', addDefect: 'Mangel hinzufügen',
    removeDefect: 'Mangel entfernen', noDefects: 'Keine Mängel erfasst.', followUp: 'Erledigung',
    resolvedAt: 'Erledigt am', resolutionNote: 'Vermerk', saveFollowUp: 'Erledigung speichern',
    followUpHint: 'Die Erledigung gehört nicht zum Original und bleibt auch nach dem Abschluss änderbar.',
    keys: 'Schlüssel', keyType: 'Art', keyLabel: 'Bezeichnung', handedOver: 'Übergeben', handedOverMoveOut: 'Ausgehändigt',
    returned: 'Zurückgegeben', missingKeys: 'Fehlend: {{count}}', addKey: 'Schlüssel hinzufügen',
    removeKey: 'Schlüssel entfernen', noKeys: 'Keine Schlüssel erfasst.',
    key_house_door: 'Haustür', key_apartment_door: 'Wohnungstür', key_mailbox: 'Briefkasten', key_cellar: 'Keller',
    key_garage: 'Garage / Stellplatz', key_other: 'Sonstiger',
    meters: 'Zählerstände', meterValue: 'Stand', lastReading: 'Letzte Ablesung {{value}} am {{date}}',
    noMeters: 'Die Einheit hat keine Zähler. Zähler werden unter „Zähler“ angelegt.',
    meterHint: 'Beim Abschluss werden die Stände als Ablesungen zum Übergabedatum gespeichert und von der Nebenkostenabrechnung verwendet.',
    addFreeReading: 'Stand ohne Zähler der Einheit', meterType: 'Zählerart', meterNumber: 'Zählernummer',
    meterUnit: 'Maßeinheit', removeReading: 'Stand entfernen', notInBilling: 'nicht in der Abrechnung',
    meter_cold_water: 'Kaltwasser', meter_hot_water: 'Warmwasser', meter_heating: 'Heizung', meter_electricity: 'Strom',
    meter_gas: 'Gas', meter_water: 'Wasser',
    photos: 'Fotos', protocolPhotos: 'Fotos zum Protokoll', addPhoto: 'Foto hinzufügen', removePhoto: 'Foto entfernen',
    photo: 'Foto', uploading: 'Foto wird hochgeladen …', photoHint: 'Fotos werden geschützt gespeichert und im PDF abgebildet.',
    save: 'Speichern', saved: 'Gespeichert.', dirty: 'Ungespeicherte Änderungen',
    error_date: 'Bitte ein Übergabedatum angeben.', error_roomName: 'Jeder Raum braucht eine Bezeichnung.',
    error_defectDescription: 'Jeder Mangel braucht eine Beschreibung.',
    error_keyCount: 'Schlüsselanzahlen bitte als ganze Zahl von 0 bis 999.', error_meterValue: 'Zählerstände bitte als Zahl.',
    conflictTitle: 'Inzwischen geändert', reload: 'Neu laden',
    check: 'Prüfen', checkTitle: 'Prüfung vor dem Abschluss', ready: 'Bereit zum Abschließen',
    notReady: 'Noch nicht vollständig', hints: 'Hinweise',
    counts: '{{rooms}} Räume · {{defects}} Mängel · {{keys}} Schlüsselarten · {{readings}} Zählerstände · {{photos}} Fotos',
    openPreviewPdf: 'PDF-Vorschau öffnen', previewPdfTitle: 'Vorschau des Übergabeprotokolls',
    previewInvalidated: 'Geändert: bitte erneut prüfen.',
    confirmContent: 'Ich bestätige, dass das Protokoll den gemeinsam festgestellten Zustand wiedergibt.',
    confirmSignatures: 'Ich bestätige, dass die genannten Personen das ausgedruckte Protokoll unterschreiben bzw. unterschrieben haben.',
    finalize: 'Abschließen und Original speichern',
    finalized: 'Abgeschlossen: Das PDF ist als unveränderliches Original gespeichert, die Zählerstände stehen in der Abrechnung.',
    unknownTitle: 'Verbindung unterbrochen',
    unknownBody: 'Ob der Abschluss angekommen ist, ist unklar. Der vorbereitete Abschluss kann unverändert erneut gesendet werden.',
    retryExact: 'Unverändert erneut senden',
    original: 'Original', openOriginal: 'PDF öffnen', download: 'PDF herunterladen',
    originalPdfTitle: 'Abgeschlossenes Übergabeprotokoll',
    contentMismatch: 'Achtung: Die gespeicherten Angaben weichen vom archivierten Original ab. Maßgeblich ist das Original.',
    correction: 'Korrektur anlegen', correctionOf: 'Korrektur des Protokolls vom {{date}}',
    correctionHint: 'Diese Fassung korrigiert ein abgeschlossenes Protokoll; dessen Original bleibt unverändert.',
    discardTitle: 'Ungespeicherte Änderungen verwerfen?', discardPrompt: 'Die Änderungen seit dem letzten Speichern gehen verloren.',
    keepEditing: 'Weiter bearbeiten', discardConfirm: 'Verwerfen und schließen',
    newMoveIn: 'Einzug protokollieren', newMoveOut: 'Auszug protokollieren', open: 'Öffnen',
    noProtocols: 'Für diesen Vertrag gibt es noch kein Übergabeprotokoll.', tenantChange: 'Mieterwechsel',
    previousContract: 'Vormieter: Vertrag {{number}}, Ende {{date}}', nextContract: 'Nachmieter: Vertrag {{number}}, Beginn {{date}}',
    previousMoveOut: 'Auszug des Vormieters', nextMoveIn: 'Einzug des Nachmieters',
    housingConfirmation: 'Wohnungsgeberbestätigung',
    noTemplates: 'Briefvorlagen für den Mieterwechsel sind nicht hinterlegt.',
    pageTitle: 'Übergabeprotokolle', newProtocol: 'Neues Übergabeprotokoll', create: 'Anlegen',
    deleteDraft: 'Entwurf löschen', deleteConfirm: 'Diesen Entwurf mit Räumen, Mängeln und Fotos löschen?',
    problem_NO_ROOMS: 'Mindestens einen Raum erfassen.',
    problem_LANDLORD_SIGNER_MISSING: 'Name der Person, die für den Vermieter unterschreibt, fehlt.',
    problem_TENANT_SIGNER_MISSING: 'Name des unterschreibenden Mieters fehlt.',
    problem_KEYS_RETURN_MISSING: 'Für jeden Schlüssel die zurückgegebene Anzahl eintragen.',
    problem_ROOM_NOT_ASSESSED: 'Nicht jeder Raum hat einen Zustand.',
    problem_KEYS_MISSING: 'Es fehlen Schlüssel; das Protokoll weist die Differenz aus.',
    problem_CONTRACT_END_MISSING: 'Der Vertrag hat kein Enddatum; bitte das Auszugsdatum am Vertrag eintragen.',
    problem_DATE_FAR_FROM_CONTRACT: 'Die Übergabe liegt weit vom Vertragsdatum entfernt; die Abrechnung nutzt die Stände dann nicht als Stand zum Mieterwechsel.',
    problem_METER_NOT_READ: 'Nicht jeder Zähler hat einen Stand; die Abrechnung teilt den Verbrauch dann nach Tagen.',
    problem_METER_READING_CONFLICT: 'Für einen Zähler gibt es am Übergabedatum bereits einen anderen Stand.',
    problem_CORRECTION_DROPS_METER: 'Die Korrektur muss jeden Zähler des korrigierten Protokolls enthalten.',
  },
  'en-US': {
    action: 'Handover protocols', title: 'Handover protocol', eyebrow: 'Tenant change', listTitle: 'Handover protocols',
    close: 'Close', back: 'Back to the protocol', loading: 'Loading …',
    loadFailed: 'The handover protocol could not be loaded.', retry: 'Try again',
    readOnly: 'Read-only access: your role may not change handover protocols.',
    type_move_in: 'Move-in', type_move_out: 'Move-out',
    state_draft: 'Draft', state_correction: 'Correction (draft)', state_finalized: 'Finalized',
    state_superseded: 'Superseded by a correction',
    legacyFinalized: 'Marked "finalized" by hand earlier – there is no archived original. Please review and finalize.',
    contract: 'Contract', unit: 'Unit', property: 'Property', tenant: 'Tenant', date: 'Date', kind: 'Type', status: 'Status',
    general: 'General', protocolDate: 'Handover date', tenantPresent: 'Tenant present',
    landlordPresent: 'Landlord or representative present', overallCondition: 'Overall condition',
    notAssessed: 'not assessed', tenantSigner: 'Tenant signing (name)',
    landlordSigner: 'Landlord / representative signing (name)', notes: 'Notes',
    condition_good: 'good', condition_fair: 'fair', condition_poor: 'poor',
    rooms: 'Rooms', roomName: 'Room', condition: 'Condition', addRoom: 'Add room', removeRoom: 'Remove room',
    noRooms: 'No rooms recorded yet.',
    defects: 'Defects', defectRoom: 'Room', generalRoom: 'general', description: 'Description',
    responsible: 'Responsible', responsible_tenant: 'Tenant', responsible_landlord: 'Landlord',
    responsible_open: 'open / to be clarified', remedy: 'Agreement', dueDate: 'Due by', addDefect: 'Add defect',
    removeDefect: 'Remove defect', noDefects: 'No defects recorded.', followUp: 'Resolution',
    resolvedAt: 'Resolved on', resolutionNote: 'Note', saveFollowUp: 'Save resolution',
    followUpHint: 'The resolution is not part of the original and stays editable after finalization.',
    keys: 'Keys', keyType: 'Type', keyLabel: 'Label', handedOver: 'Handed over', handedOverMoveOut: 'Issued',
    returned: 'Returned', missingKeys: 'Missing: {{count}}', addKey: 'Add key', removeKey: 'Remove key',
    noKeys: 'No keys recorded.',
    key_house_door: 'Front door', key_apartment_door: 'Apartment door', key_mailbox: 'Mailbox', key_cellar: 'Cellar',
    key_garage: 'Garage / parking', key_other: 'Other',
    meters: 'Meter readings', meterValue: 'Reading', lastReading: 'Last reading {{value}} on {{date}}',
    noMeters: 'The unit has no meters. Meters are created under "Meters".',
    meterHint: 'On finalization the readings are stored as meter readings on the handover date and used by the utility billing.',
    addFreeReading: 'Reading without a unit meter', meterType: 'Meter type', meterNumber: 'Meter number',
    meterUnit: 'Unit of measure', removeReading: 'Remove reading', notInBilling: 'not in the billing',
    meter_cold_water: 'Cold water', meter_hot_water: 'Hot water', meter_heating: 'Heating', meter_electricity: 'Electricity',
    meter_gas: 'Gas', meter_water: 'Water',
    photos: 'Photos', protocolPhotos: 'Photos of the protocol', addPhoto: 'Add photo', removePhoto: 'Remove photo',
    photo: 'Photo', uploading: 'Uploading photo …', photoHint: 'Photos are stored protected and shown in the PDF.',
    save: 'Save', saved: 'Saved.', dirty: 'Unsaved changes',
    error_date: 'Please enter a handover date.', error_roomName: 'Every room needs a name.',
    error_defectDescription: 'Every defect needs a description.',
    error_keyCount: 'Key counts must be whole numbers from 0 to 999.', error_meterValue: 'Meter readings must be numbers.',
    conflictTitle: 'Changed meanwhile', reload: 'Reload',
    check: 'Check', checkTitle: 'Check before finalizing', ready: 'Ready to finalize', notReady: 'Not complete yet',
    hints: 'Notes',
    counts: '{{rooms}} rooms · {{defects}} defects · {{keys}} key types · {{readings}} readings · {{photos}} photos',
    openPreviewPdf: 'Open PDF preview', previewPdfTitle: 'Handover protocol preview',
    previewInvalidated: 'Changed: please check again.',
    confirmContent: 'I confirm that the protocol reflects the condition established together.',
    confirmSignatures: 'I confirm that the named persons sign or have signed the printed protocol.',
    finalize: 'Finalize and store the original',
    finalized: 'Finalized: the PDF is stored as an immutable original, the readings are in the billing.',
    unknownTitle: 'Connection interrupted',
    unknownBody: 'It is unclear whether the finalization arrived. The prepared finalization can be sent again unchanged.',
    retryExact: 'Send again unchanged',
    original: 'Original', openOriginal: 'Open PDF', download: 'Download PDF',
    originalPdfTitle: 'Finalized handover protocol',
    contentMismatch: 'Attention: the stored details differ from the archived original. The original prevails.',
    correction: 'Create correction', correctionOf: 'Correction of the protocol of {{date}}',
    correctionHint: 'This version corrects a finalized protocol; its original stays unchanged.',
    discardTitle: 'Discard unsaved changes?', discardPrompt: 'The changes since the last save will be lost.',
    keepEditing: 'Keep editing', discardConfirm: 'Discard and close',
    newMoveIn: 'Record move-in', newMoveOut: 'Record move-out', open: 'Open',
    noProtocols: 'There is no handover protocol for this contract yet.', tenantChange: 'Tenant change',
    previousContract: 'Previous tenant: contract {{number}}, end {{date}}',
    nextContract: 'Next tenant: contract {{number}}, start {{date}}',
    previousMoveOut: 'Move-out of the previous tenant', nextMoveIn: 'Move-in of the next tenant',
    housingConfirmation: 'Housing provider confirmation',
    noTemplates: 'No letter templates for a tenant change are available.',
    pageTitle: 'Handover protocols', newProtocol: 'New handover protocol', create: 'Create',
    deleteDraft: 'Delete draft', deleteConfirm: 'Delete this draft with its rooms, defects and photos?',
    problem_NO_ROOMS: 'Record at least one room.',
    problem_LANDLORD_SIGNER_MISSING: 'The name of the person signing for the landlord is missing.',
    problem_TENANT_SIGNER_MISSING: 'The name of the tenant signing is missing.',
    problem_KEYS_RETURN_MISSING: 'Enter the returned count for every key.',
    problem_ROOM_NOT_ASSESSED: 'Not every room has a condition.',
    problem_KEYS_MISSING: 'Keys are missing; the protocol shows the difference.',
    problem_CONTRACT_END_MISSING: 'The contract has no end date; please enter the move-out date on the contract.',
    problem_DATE_FAR_FROM_CONTRACT: 'The handover is far from the contract date; the billing will not use these readings for the tenant change.',
    problem_METER_NOT_READ: 'Not every meter has a reading; the billing then splits the consumption by days.',
    problem_METER_READING_CONFLICT: 'A meter already has a different reading on the handover date.',
    problem_CORRECTION_DROPS_METER: 'The correction must contain every meter of the corrected protocol.',
  },
  'es-ES': {
    action: 'Actas de entrega', title: 'Acta de entrega', eyebrow: 'Cambio de inquilino', listTitle: 'Actas de entrega',
    close: 'Cerrar', back: 'Volver al acta', loading: 'Cargando …',
    loadFailed: 'No se pudo cargar el acta de entrega.', retry: 'Reintentar',
    readOnly: 'Solo lectura: su rol no puede modificar actas de entrega.',
    type_move_in: 'Entrada', type_move_out: 'Salida',
    state_draft: 'Borrador', state_correction: 'Corrección (borrador)', state_finalized: 'Cerrada',
    state_superseded: 'Sustituida por una corrección',
    legacyFinalized: 'Marcada antes a mano como «cerrada»: no hay original archivado. Revísela y ciérrela.',
    contract: 'Contrato', unit: 'Unidad', property: 'Inmueble', tenant: 'Inquilino', date: 'Fecha', kind: 'Tipo',
    status: 'Estado',
    general: 'General', protocolDate: 'Fecha de entrega', tenantPresent: 'Inquilino presente',
    landlordPresent: 'Arrendador o representante presente', overallCondition: 'Estado general',
    notAssessed: 'sin evaluar', tenantSigner: 'Firma del inquilino (nombre)',
    landlordSigner: 'Firma del arrendador / representante (nombre)', notes: 'Observaciones',
    condition_good: 'bueno', condition_fair: 'aceptable', condition_poor: 'deficiente',
    rooms: 'Estancias', roomName: 'Estancia', condition: 'Estado', addRoom: 'Añadir estancia',
    removeRoom: 'Quitar estancia', noRooms: 'Aún no hay estancias.',
    defects: 'Defectos', defectRoom: 'Estancia', generalRoom: 'general', description: 'Descripción',
    responsible: 'Responsable', responsible_tenant: 'Inquilino', responsible_landlord: 'Arrendador',
    responsible_open: 'abierto / por aclarar', remedy: 'Acuerdo', dueDate: 'Plazo', addDefect: 'Añadir defecto',
    removeDefect: 'Quitar defecto', noDefects: 'No hay defectos.', followUp: 'Resolución',
    resolvedAt: 'Resuelto el', resolutionNote: 'Nota', saveFollowUp: 'Guardar resolución',
    followUpHint: 'La resolución no forma parte del original y sigue editable tras el cierre.',
    keys: 'Llaves', keyType: 'Tipo', keyLabel: 'Descripción', handedOver: 'Entregadas', handedOverMoveOut: 'Entregadas',
    returned: 'Devueltas', missingKeys: 'Faltan: {{count}}', addKey: 'Añadir llave', removeKey: 'Quitar llave',
    noKeys: 'No hay llaves.',
    key_house_door: 'Portal', key_apartment_door: 'Puerta de la vivienda', key_mailbox: 'Buzón', key_cellar: 'Trastero',
    key_garage: 'Garaje / plaza', key_other: 'Otra',
    meters: 'Lecturas de contadores', meterValue: 'Lectura', lastReading: 'Última lectura {{value}} el {{date}}',
    noMeters: 'La unidad no tiene contadores. Los contadores se crean en «Contadores».',
    meterHint: 'Al cerrar, las lecturas se guardan con la fecha de entrega y las usa la liquidación de gastos.',
    addFreeReading: 'Lectura sin contador de la unidad', meterType: 'Tipo de contador', meterNumber: 'Número de contador',
    meterUnit: 'Unidad de medida', removeReading: 'Quitar lectura', notInBilling: 'fuera de la liquidación',
    meter_cold_water: 'Agua fría', meter_hot_water: 'Agua caliente', meter_heating: 'Calefacción',
    meter_electricity: 'Electricidad', meter_gas: 'Gas', meter_water: 'Agua',
    photos: 'Fotos', protocolPhotos: 'Fotos del acta', addPhoto: 'Añadir foto', removePhoto: 'Quitar foto',
    photo: 'Foto', uploading: 'Subiendo foto …', photoHint: 'Las fotos se guardan protegidas y aparecen en el PDF.',
    save: 'Guardar', saved: 'Guardado.', dirty: 'Cambios sin guardar',
    error_date: 'Indique la fecha de entrega.', error_roomName: 'Cada estancia necesita un nombre.',
    error_defectDescription: 'Cada defecto necesita una descripción.',
    error_keyCount: 'Las llaves deben ser números enteros de 0 a 999.', error_meterValue: 'Las lecturas deben ser números.',
    conflictTitle: 'Modificada entretanto', reload: 'Recargar',
    check: 'Comprobar', checkTitle: 'Comprobación antes del cierre', ready: 'Lista para cerrar',
    notReady: 'Aún incompleta', hints: 'Avisos',
    counts: '{{rooms}} estancias · {{defects}} defectos · {{keys}} tipos de llave · {{readings}} lecturas · {{photos}} fotos',
    openPreviewPdf: 'Abrir vista previa PDF', previewPdfTitle: 'Vista previa del acta de entrega',
    previewInvalidated: 'Modificada: vuelva a comprobar.',
    confirmContent: 'Confirmo que el acta refleja el estado constatado conjuntamente.',
    confirmSignatures: 'Confirmo que las personas indicadas firman o han firmado el acta impresa.',
    finalize: 'Cerrar y guardar el original',
    finalized: 'Cerrada: el PDF se guarda como original inalterable y las lecturas están en la liquidación.',
    unknownTitle: 'Conexión interrumpida',
    unknownBody: 'No está claro si el cierre llegó. El cierre preparado puede enviarse de nuevo sin cambios.',
    retryExact: 'Enviar de nuevo sin cambios',
    original: 'Original', openOriginal: 'Abrir PDF', download: 'Descargar PDF', originalPdfTitle: 'Acta de entrega cerrada',
    contentMismatch: 'Atención: los datos guardados difieren del original archivado. Prevalece el original.',
    correction: 'Crear corrección', correctionOf: 'Corrección del acta del {{date}}',
    correctionHint: 'Esta versión corrige un acta cerrada; su original no cambia.',
    discardTitle: '¿Descartar los cambios sin guardar?', discardPrompt: 'Se perderán los cambios desde el último guardado.',
    keepEditing: 'Seguir editando', discardConfirm: 'Descartar y cerrar',
    newMoveIn: 'Registrar entrada', newMoveOut: 'Registrar salida', open: 'Abrir',
    noProtocols: 'Este contrato aún no tiene acta de entrega.', tenantChange: 'Cambio de inquilino',
    previousContract: 'Inquilino anterior: contrato {{number}}, fin {{date}}',
    nextContract: 'Inquilino siguiente: contrato {{number}}, inicio {{date}}',
    previousMoveOut: 'Salida del inquilino anterior', nextMoveIn: 'Entrada del inquilino siguiente',
    housingConfirmation: 'Confirmación del arrendador',
    noTemplates: 'No hay plantillas de cartas para el cambio de inquilino.',
    pageTitle: 'Actas de entrega', newProtocol: 'Nueva acta de entrega', create: 'Crear',
    deleteDraft: 'Eliminar borrador', deleteConfirm: '¿Eliminar este borrador con sus estancias, defectos y fotos?',
    problem_NO_ROOMS: 'Registre al menos una estancia.',
    problem_LANDLORD_SIGNER_MISSING: 'Falta el nombre de quien firma por el arrendador.',
    problem_TENANT_SIGNER_MISSING: 'Falta el nombre del inquilino que firma.',
    problem_KEYS_RETURN_MISSING: 'Indique las llaves devueltas de cada tipo.',
    problem_ROOM_NOT_ASSESSED: 'No todas las estancias tienen estado.',
    problem_KEYS_MISSING: 'Faltan llaves; el acta muestra la diferencia.',
    problem_CONTRACT_END_MISSING: 'El contrato no tiene fecha de fin; indíquela en el contrato.',
    problem_DATE_FAR_FROM_CONTRACT: 'La entrega está lejos de la fecha del contrato; la liquidación no usará estas lecturas para el cambio.',
    problem_METER_NOT_READ: 'No todos los contadores tienen lectura; la liquidación reparte entonces por días.',
    problem_METER_READING_CONFLICT: 'Un contador ya tiene otra lectura en la fecha de entrega.',
    problem_CORRECTION_DROPS_METER: 'La corrección debe contener todos los contadores del acta corregida.',
  },
};

export function handoverText(locale = 'de-DE', key, params = {}) {
  const table = COPY[locale] || COPY['de-DE'];
  let value = table[key] ?? COPY['de-DE'][key] ?? key;
  for (const [name, replacement] of Object.entries(params)) {
    value = value.replaceAll(`{{${name}}}`, String(replacement));
  }
  return value;
}
