import { useTranslation } from '../../i18n';

const de = {
  party: 'Mieterinformationen', close: 'Schließen', overview: 'Übersicht', documents: 'Dokumente', active: 'Aktiv', archived: 'Archiviert', contact: 'Kontakt', email: 'E-Mail', phone: 'Telefon', address: 'Adresse', copy: 'Kopieren', copied: 'Kopiert', copyFailed: 'Kopieren fehlgeschlagen.', noContact: 'Keine Kontaktdaten hinterlegt.', notes: 'Notizen', noNotes: 'Keine Notizen hinterlegt.', contracts: 'Verträge', current: 'Aktuelle Verträge', history: 'Frühere Verträge', upcoming: 'Künftige Verträge', drafts: 'Entwürfe', terminated: 'Gekündigt', expired: 'Abgelaufen', draft: 'Entwurf', noContracts: 'Keine Verträge vorhanden.', contract: 'Vertrag', property: 'Immobilie', unit: 'Einheit', start: 'Beginn', end: 'Ende', openEnded: 'Unbefristet', coldRent: 'Kaltmiete', serviceCharge: 'Nebenkosten', heatingCharge: 'Heizkosten', rentMissing: 'Keine Vertragsmiete hinterlegt.', rentDate: 'Miete gültig ab', account: 'Mieterkonto', edit: 'Mieter bearbeiten', upload: 'Dokument hinzufügen', allDocuments: 'Dokumentenverwaltung', search: 'Dokumente durchsuchen', searchPlaceholder: 'Titel, Beschreibung oder Schlagwort …', type: 'Dokumententyp', allTypes: 'Alle Typen', allContracts: 'Alle Verträge', grid: 'Kartenansicht', list: 'Listenansicht', newest: 'Neueste zuerst', noDocuments: 'Noch keine Dokumente', noDocumentsHelp: 'Hier erscheinen Dokumente dieses Mieters und seiner Verträge.', noMatches: 'Keine passenden Dokumente', noMatchesHelp: 'Passen Sie die Suche oder die Filter an.', loading: 'Wird geladen …', loadingMore: 'Weitere Dokumente werden geladen …', more: 'Weitere Dokumente laden', retry: 'Erneut versuchen', loadFailed: 'Die Informationen konnten nicht geladen werden.', documentFailed: 'Die Dokumente konnten nicht geladen werden.', previousResults: 'Die bisher geladenen Dokumente bleiben sichtbar.', count: 'angezeigt', preview: 'Vorschau', download: 'Herunterladen', downloading: 'Wird heruntergeladen …', downloadFailed: 'Die Datei konnte nicht heruntergeladen werden.', noFile: 'Keine Datei vorhanden', invalidFile: 'Die Dateiadresse ist ungültig.', unknownType: 'Dokument', date: 'Datum', fileView: 'Dateiansicht', open: 'Öffnen', original: 'Original', ocr: 'OCR-Text', copyText: 'Text kopieren', noPreview: 'Vorschau nicht verfügbar', imageFailed: 'Die Vorschau konnte nicht geladen werden.', readOnly: 'Nur Lesezugriff', contractDocs: 'Dokumente zu diesem Vertrag', clearFilters: 'Filter zurücksetzen', contactCopied: 'Kontaktdaten kopieren', unknownParty: 'Mieter', noDate: 'Ohne Datum', resultCount: 'Dokumente', emptyValue: 'Nicht hinterlegt', moreUnavailable: 'Weitere Seiten konnten nicht geladen werden.'
};
const en = {
  party: 'Tenant information', close: 'Close', overview: 'Overview', documents: 'Documents', active: 'Active', archived: 'Archived', contact: 'Contact', email: 'Email', phone: 'Phone', address: 'Address', copy: 'Copy', copied: 'Copied', copyFailed: 'Copy failed.', noContact: 'No contact details available.', notes: 'Notes', noNotes: 'No notes available.', contracts: 'Contracts', current: 'Current contracts', history: 'Previous contracts', upcoming: 'Future contracts', drafts: 'Drafts', terminated: 'Terminated', expired: 'Expired', draft: 'Draft', noContracts: 'No contracts available.', contract: 'Contract', property: 'Property', unit: 'Unit', start: 'Start', end: 'End', openEnded: 'Open-ended', coldRent: 'Base rent', serviceCharge: 'Service charges', heatingCharge: 'Heating charges', rentMissing: 'No contract rent available.', rentDate: 'Rent effective from', account: 'Tenant account', edit: 'Edit tenant', upload: 'Add document', allDocuments: 'Manage documents', search: 'Search documents', searchPlaceholder: 'Title, description or tag …', type: 'Document type', allTypes: 'All types', allContracts: 'All contracts', grid: 'Card view', list: 'List view', newest: 'Newest first', noDocuments: 'No documents yet', noDocumentsHelp: 'Documents belonging to this tenant and their contracts appear here.', noMatches: 'No matching documents', noMatchesHelp: 'Adjust the search or filters.', loading: 'Loading …', loadingMore: 'Loading more documents …', more: 'Load more documents', retry: 'Try again', loadFailed: 'The information could not be loaded.', documentFailed: 'The documents could not be loaded.', previousResults: 'Previously loaded documents remain visible.', count: 'shown', preview: 'Preview', download: 'Download', downloading: 'Downloading …', downloadFailed: 'The file could not be downloaded.', noFile: 'No file available', invalidFile: 'The file address is invalid.', unknownType: 'Document', date: 'Date', fileView: 'File preview', open: 'Open', original: 'Original', ocr: 'OCR text', copyText: 'Copy text', noPreview: 'Preview unavailable', imageFailed: 'The preview could not be loaded.', readOnly: 'Read-only access', contractDocs: 'Documents for this contract', clearFilters: 'Reset filters', contactCopied: 'Copy contact details', unknownParty: 'Tenant', noDate: 'No date', resultCount: 'documents', emptyValue: 'Not available', moreUnavailable: 'Additional pages could not be loaded.'
};
const es = {
  party: 'Información del inquilino', close: 'Cerrar', overview: 'Resumen', documents: 'Documentos', active: 'Activo', archived: 'Archivado', contact: 'Contacto', email: 'Correo electrónico', phone: 'Teléfono', address: 'Dirección', copy: 'Copiar', copied: 'Copiado', copyFailed: 'No se pudo copiar.', noContact: 'No hay datos de contacto.', notes: 'Notas', noNotes: 'No hay notas.', contracts: 'Contratos', current: 'Contratos actuales', history: 'Contratos anteriores', upcoming: 'Contratos futuros', drafts: 'Borradores', terminated: 'Rescindido', expired: 'Vencido', draft: 'Borrador', noContracts: 'No hay contratos.', contract: 'Contrato', property: 'Inmueble', unit: 'Unidad', start: 'Inicio', end: 'Fin', openEnded: 'Indefinido', coldRent: 'Alquiler base', serviceCharge: 'Gastos comunes', heatingCharge: 'Calefacción', rentMissing: 'No hay alquiler del contrato.', rentDate: 'Alquiler vigente desde', account: 'Cuenta del inquilino', edit: 'Editar inquilino', upload: 'Añadir documento', allDocuments: 'Gestionar documentos', search: 'Buscar documentos', searchPlaceholder: 'Título, descripción o etiqueta …', type: 'Tipo de documento', allTypes: 'Todos los tipos', allContracts: 'Todos los contratos', grid: 'Vista de tarjetas', list: 'Vista de lista', newest: 'Más recientes primero', noDocuments: 'Todavía no hay documentos', noDocumentsHelp: 'Aquí aparecen los documentos del inquilino y sus contratos.', noMatches: 'No hay documentos coincidentes', noMatchesHelp: 'Ajuste la búsqueda o los filtros.', loading: 'Cargando …', loadingMore: 'Cargando más documentos …', more: 'Cargar más documentos', retry: 'Reintentar', loadFailed: 'No se pudo cargar la información.', documentFailed: 'No se pudieron cargar los documentos.', previousResults: 'Los documentos ya cargados siguen visibles.', count: 'mostrados', preview: 'Vista previa', download: 'Descargar', downloading: 'Descargando …', downloadFailed: 'No se pudo descargar el archivo.', noFile: 'No hay archivo', invalidFile: 'La dirección del archivo no es válida.', unknownType: 'Documento', date: 'Fecha', fileView: 'Vista del archivo', open: 'Abrir', original: 'Original', ocr: 'Texto OCR', copyText: 'Copiar texto', noPreview: 'Vista previa no disponible', imageFailed: 'No se pudo cargar la vista previa.', readOnly: 'Solo lectura', contractDocs: 'Documentos de este contrato', clearFilters: 'Restablecer filtros', contactCopied: 'Copiar datos de contacto', unknownParty: 'Inquilino', noDate: 'Sin fecha', resultCount: 'documentos', emptyValue: 'No disponible', moreUnavailable: 'No se pudieron cargar más páginas.'
};

export function usePartyText() {
  const { locale } = useTranslation();
  return { text: locale?.startsWith('en') ? en : locale?.startsWith('es') ? es : de, locale: locale || 'de-DE' };
}
